"""取引価格データ ETL: land_price_api_app の DuckDB → SQL INSERT 出力。

使い方:
    uv run python scripts/etl_trade_prices.py --output /tmp/trade_prices.sql
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def find_duckdb() -> Path:
    env = os.getenv("DUCKDB_PATH")
    if env:
        return Path(env)
    candidates = [
        Path(__file__).parent.parent.parent
        / "_data"
        / "land_price"
        / "processed"
        / "land_prices.duckdb",
        Path(__file__).parent.parent.parent
        / "land_price_api_app"
        / "data"
        / "processed"
        / "land_prices.duckdb",
    ]
    for c in candidates:
        if c.exists():
            return c
    raise FileNotFoundError("DuckDB が見つかりません。DUCKDB_PATH 環境変数で指定してください。")


def export_trade_prices(duckdb_path: Path, output: Path, limit: int) -> int:
    import duckdb

    con = duckdb.connect(str(duckdb_path), read_only=True)
    # trade_prices テーブルが存在するか確認
    tables = [r[0] for r in con.execute("SHOW TABLES").fetchall()]
    if "trade_prices" not in tables:
        print("WARNING: trade_prices テーブルが見つかりません", file=sys.stderr)
        con.close()
        return 0

    rows = con.execute(
        f"""
        SELECT
            id,
            pref_code,
            city_code,
            address,
            lat,
            lng,
            year,
            quarter,
            transaction_type,
            price_yen,
            area_sqm,
            price_per_sqm,
            building_age,
            structure,
            land_use
        FROM trade_prices
        LIMIT {limit}
        """
    ).fetchall()
    con.close()

    lines = [
        "-- Trade Prices (取引価格)",
        "-- Generated by scripts/etl_trade_prices.py",
        "",
        "CREATE TABLE IF NOT EXISTS trade_prices (",
        "  id TEXT PRIMARY KEY,",
        "  pref_code TEXT,",
        "  city_code TEXT,",
        "  address TEXT,",
        "  lat DOUBLE PRECISION,",
        "  lng DOUBLE PRECISION,",
        "  year INTEGER,",
        "  quarter INTEGER,",
        "  transaction_type TEXT,",
        "  price_yen BIGINT,",
        "  area_sqm DOUBLE PRECISION,",
        "  price_per_sqm INTEGER,",
        "  building_age INTEGER,",
        "  structure TEXT,",
        "  land_use TEXT",
        ");",
        "",
    ]
    for row in rows:
        vals = ", ".join(
            "NULL"
            if v is None
            else f"'{str(v).replace(chr(39), chr(39) * 2)}'"
            if isinstance(v, str)
            else str(v)
            for v in row
        )
        lines.append(f"INSERT INTO trade_prices VALUES ({vals}) ON CONFLICT (id) DO NOTHING;")

    output.write_text("\n".join(lines), encoding="utf-8")
    return len(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="取引価格 ETL → SQL")
    parser.add_argument("--output", default="/tmp/trade_prices.sql")
    parser.add_argument("--limit", type=int, default=100_000)
    args = parser.parse_args()

    try:
        db = find_duckdb()
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    out = Path(args.output)
    n = export_trade_prices(db, out, args.limit)
    print(f"Exported {n:,} rows → {out}")


if __name__ == "__main__":
    main()
