"""賃料市場データ ETL: land_price_api_app の DuckDB → SQL INSERT 出力。"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def find_duckdb() -> Path:
    env = os.getenv("DUCKDB_PATH")
    if env:
        return Path(env)
    candidates = [
        Path(__file__).parent.parent.parent
        / "_data"
        / "land_price"
        / "processed"
        / "land_prices.duckdb",
    ]
    for c in candidates:
        if c.exists():
            return c
    raise FileNotFoundError("DuckDB が見つかりません。DUCKDB_PATH 環境変数で指定してください。")


def export_rent_market(duckdb_path: Path, output: Path, limit: int) -> int:
    import duckdb

    con = duckdb.connect(str(duckdb_path), read_only=True)
    tables = [r[0] for r in con.execute("SHOW TABLES").fetchall()]
    if "rent_market" not in tables:
        print("WARNING: rent_market テーブルが見つかりません", file=sys.stderr)
        con.close()
        return 0

    rows = con.execute(f"SELECT * FROM rent_market LIMIT {limit}").fetchall()
    cols = [d[0] for d in con.execute("DESCRIBE rent_market").fetchall()]
    con.close()

    col_defs = "\n".join(f"  {c} TEXT," for c in cols).rstrip(",")
    lines = [
        "-- Rent Market (賃料市場)",
        "-- Generated by scripts/etl_rent_market.py",
        "",
        "CREATE TABLE IF NOT EXISTS rent_market (",
        col_defs,
        ");",
        "",
    ]
    col_str = ", ".join(cols)
    for row in rows:
        vals = ", ".join(
            "NULL" if v is None else f"'{str(v).replace(chr(39), chr(39) * 2)}'" for v in row
        )
        lines.append(f"INSERT INTO rent_market ({col_str}) VALUES ({vals}) ON CONFLICT DO NOTHING;")

    output.write_text("\n".join(lines), encoding="utf-8")
    return len(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="賃料市場 ETL → SQL")
    parser.add_argument("--output", default="/tmp/rent_market.sql")
    parser.add_argument("--limit", type=int, default=50_000)
    args = parser.parse_args()

    try:
        db = find_duckdb()
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    out = Path(args.output)
    n = export_rent_market(db, out, args.limit)
    print(f"Exported {n:,} rows → {out}")


if __name__ == "__main__":
    main()
