"""公示地価データ ETL: land_price_api_app の DuckDB → SQL INSERT 出力。

使い方:
    uv run python scripts/etl_public_notice.py --output /tmp/public_notice.sql
    # 出力 SQL を Supabase で実行する

依存:
    uv run pip install duckdb

環境変数:
    DUCKDB_PATH  PoC DuckDB のパス (省略時: ../_data/land_price/processed/land_prices.duckdb)
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def find_duckdb() -> Path:
    env = os.getenv("DUCKDB_PATH")
    if env:
        return Path(env)
    candidates = [
        Path(__file__).parent.parent.parent
        / "_data"
        / "land_price"
        / "processed"
        / "land_prices.duckdb",
        Path(__file__).parent.parent.parent
        / "land_price_api_app"
        / "data"
        / "processed"
        / "land_prices.duckdb",
    ]
    for c in candidates:
        if c.exists():
            return c
    raise FileNotFoundError(
        "DuckDB が見つかりません。DUCKDB_PATH 環境変数で指定してください。\n"
        f"探した場所: {[str(c) for c in candidates]}"
    )


def export_public_notice(duckdb_path: Path, output: Path, limit: int) -> int:
    import duckdb

    con = duckdb.connect(str(duckdb_path), read_only=True)
    rows = con.execute(
        f"""
        SELECT
            point_id,
            year,
            pref_code,
            city_code,
            address,
            lat,
            lng,
            land_use,
            price_per_sqm,
            area_sqm,
            building_ratio,
            floor_ratio,
            structure
        FROM land_prices_public_notice
        LIMIT {limit}
        """
    ).fetchall()
    con.close()

    lines = [
        "-- Public Notice Land Price (公示地価)",
        "-- Generated by scripts/etl_public_notice.py",
        "-- Import to Supabase: psql $DATABASE_URL -f this_file.sql",
        "",
        "CREATE TABLE IF NOT EXISTS public_notice_prices (",
        "  point_id TEXT,",
        "  year INTEGER,",
        "  pref_code TEXT,",
        "  city_code TEXT,",
        "  address TEXT,",
        "  lat DOUBLE PRECISION,",
        "  lng DOUBLE PRECISION,",
        "  land_use TEXT,",
        "  price_per_sqm INTEGER,",
        "  area_sqm DOUBLE PRECISION,",
        "  building_ratio DOUBLE PRECISION,",
        "  floor_ratio DOUBLE PRECISION,",
        "  structure TEXT,",
        "  PRIMARY KEY (point_id, year)",
        ");",
        "",
    ]
    for row in rows:
        vals = ", ".join(
            "NULL" if v is None else f"'{v}'" if isinstance(v, str) else str(v) for v in row
        )
        lines.append(
            f"INSERT INTO public_notice_prices VALUES ({vals})"
            " ON CONFLICT (point_id, year) DO NOTHING;"
        )

    output.write_text("\n".join(lines), encoding="utf-8")
    return len(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="公示地価 ETL → SQL")
    parser.add_argument("--output", default="/tmp/public_notice.sql")
    parser.add_argument("--limit", type=int, default=100_000)
    args = parser.parse_args()

    try:
        db = find_duckdb()
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Source: {db}")
    out = Path(args.output)
    n = export_public_notice(db, out, args.limit)
    print(f"Exported {n:,} rows → {out}")


if __name__ == "__main__":
    main()
