"""Small, explicit coupon-bond pricing primitives for the B1 curve project.

Prices are generated by discounting every cash flow with a zero curve.  A
bond's yield to maturity is a separate scalar internal rate of return; it is
not the zero rate observed at the bond's final maturity.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Literal

import numpy as np
import pandas as pd
from numpy.random import Generator
from numpy.typing import ArrayLike, NDArray
from scipy.optimize import brentq, least_squares

from .curves import CurveBasisSpec, _basis_matrix, _curve_spec

FloatArray = NDArray[np.float64]
ZeroCurve = Callable[[FloatArray], ArrayLike]
Compounding = Literal["continuous", "annual", "periodic"]
Seed = int | np.integer | Generator | None


def _cashflow_vectors(
    cashflow_times: ArrayLike, cashflows: ArrayLike
) -> tuple[FloatArray, FloatArray]:
    times = np.asarray(cashflow_times, dtype=float)
    amounts = np.asarray(cashflows, dtype=float)
    if times.ndim != 1 or amounts.ndim != 1 or times.size == 0:
        raise ValueError("cashflow_times and cashflows must be non-empty vectors")
    if times.shape != amounts.shape:
        raise ValueError("cashflow_times and cashflows must have the same shape")
    if not np.all(np.isfinite(times)) or np.any(times <= 0.0):
        raise ValueError("cashflow_times must be finite and strictly positive")
    if np.any(np.diff(times) <= 0.0):
        raise ValueError("cashflow_times must be strictly increasing")
    if not np.all(np.isfinite(amounts)) or np.any(amounts < 0.0):
        raise ValueError("cashflows must be finite and non-negative")
    if not np.any(amounts > 0.0):
        raise ValueError("at least one cash flow must be positive")
    return times, amounts


def _frequency(value: int) -> int:
    if isinstance(value, bool) or not isinstance(value, (int, np.integer)):
        raise TypeError("frequency must be an integer")
    if value <= 0:
        raise ValueError("frequency must be strictly positive")
    return int(value)


def discount_factors(
    times: ArrayLike,
    zero_rates: ArrayLike,
    *,
    compounding: Compounding = "continuous",
    frequency: int = 2,
) -> FloatArray:
    """Convert decimal zero rates to discount factors at matching times."""

    maturity = np.asarray(times, dtype=float)
    rates = np.asarray(zero_rates, dtype=float)
    if maturity.ndim != 1 or maturity.size == 0:
        raise ValueError("times must be a non-empty vector")
    if rates.ndim == 0:
        rates = np.full_like(maturity, float(rates))
    if rates.shape != maturity.shape:
        raise ValueError("zero_rates must be scalar or have one value per time")
    if not np.all(np.isfinite(maturity)) or np.any(maturity < 0.0):
        raise ValueError("times must be finite and non-negative")
    if not np.all(np.isfinite(rates)):
        raise ValueError("zero_rates must be finite")
    frequency = _frequency(frequency)

    if compounding == "continuous":
        return np.exp(-rates * maturity)
    if compounding == "annual":
        if np.any(rates <= -1.0):
            raise ValueError("annual-compounded rates must be greater than -1")
        return (1.0 + rates) ** (-maturity)
    if compounding == "periodic":
        if np.any(rates <= -frequency):
            raise ValueError("periodic rates must be greater than -frequency")
        return (1.0 + rates / frequency) ** (-frequency * maturity)
    raise ValueError(f"unknown compounding convention: {compounding!r}")


def coupon_bond_cashflows(
    maturity_years: float,
    coupon_rate: float,
    *,
    frequency: int = 2,
    face_value: float = 100.0,
) -> tuple[FloatArray, FloatArray]:
    """Create regular coupon dates and cash flows for a simplified bond.

    The maturity must fall on a regular coupon date.  Stub periods, accrued
    interest, settlement calendars, and tax conventions are intentionally
    outside this educational primitive.
    """

    frequency = _frequency(frequency)
    if not np.isfinite(maturity_years) or maturity_years <= 0.0:
        raise ValueError("maturity_years must be finite and strictly positive")
    if not np.isfinite(coupon_rate) or coupon_rate < 0.0:
        raise ValueError("coupon_rate must be finite and non-negative")
    if not np.isfinite(face_value) or face_value <= 0.0:
        raise ValueError("face_value must be finite and strictly positive")
    periods_float = maturity_years * frequency
    periods = round(periods_float)
    if periods < 1 or not np.isclose(periods_float, periods, rtol=0.0, atol=1e-10):
        raise ValueError("maturity_years must fall on a regular coupon date")
    times = np.arange(1, periods + 1, dtype=float) / frequency
    amounts = np.full(periods, face_value * coupon_rate / frequency)
    amounts[-1] += face_value
    return times, amounts


def price_coupon_bond(
    cashflow_times: ArrayLike,
    cashflows: ArrayLike,
    zero_curve: ZeroCurve,
    *,
    compounding: Compounding = "continuous",
    frequency: int = 2,
) -> float:
    """Price a coupon bond from a zero curve by cash-flow discounting."""

    times, amounts = _cashflow_vectors(cashflow_times, cashflows)
    if not callable(zero_curve):
        raise TypeError("zero_curve must be callable")
    rates = np.asarray(zero_curve(times), dtype=float)
    if rates.ndim == 0:
        rates = np.full_like(times, float(rates))
    factors = discount_factors(times, rates, compounding=compounding, frequency=frequency)
    return float(amounts @ factors)


def price_coupon_bond_from_yield(
    cashflow_times: ArrayLike,
    cashflows: ArrayLike,
    yield_to_maturity: float,
    *,
    compounding: Compounding = "periodic",
    frequency: int = 2,
) -> float:
    """Price cash flows from one scalar YTM under an explicit convention."""

    times, amounts = _cashflow_vectors(cashflow_times, cashflows)
    frequency = _frequency(frequency)
    if not np.isfinite(yield_to_maturity):
        raise ValueError("yield_to_maturity must be finite")
    factors = discount_factors(
        times,
        yield_to_maturity,
        compounding=compounding,
        frequency=frequency,
    )
    return float(amounts @ factors)


def yield_to_maturity(
    price: float,
    cashflow_times: ArrayLike,
    cashflows: ArrayLike,
    *,
    compounding: Compounding = "periodic",
    frequency: int = 2,
) -> float:
    """Solve the scalar YTM matching a positive dirty price."""

    times, amounts = _cashflow_vectors(cashflow_times, cashflows)
    frequency = _frequency(frequency)
    if not np.isfinite(price) or price <= 0.0:
        raise ValueError("price must be finite and strictly positive")
    if compounding not in {"continuous", "annual", "periodic"}:
        raise ValueError(f"unknown compounding convention: {compounding!r}")

    def objective(rate: float) -> float:
        return (
            price_coupon_bond_from_yield(
                times,
                amounts,
                rate,
                compounding=compounding,
                frequency=frequency,
            )
            - price
        )

    if compounding == "continuous":
        lower = -1.0
        while objective(lower) < 0.0 and abs(lower) < 1e6:
            lower *= 2.0
    else:
        boundary = -1.0 if compounding == "annual" else -float(frequency)
        lower = 0.5 * boundary
        for _ in range(52):
            if objective(lower) > 0.0:
                break
            lower = boundary + 0.5 * (lower - boundary)

    upper = 1.0
    while objective(upper) > 0.0 and upper < 1e6:
        upper *= 2.0
    if objective(lower) <= 0.0 or objective(upper) > 0.0:
        raise ValueError("could not bracket a yield for the supplied price")
    try:
        return float(brentq(objective, lower, upper, xtol=1e-13, rtol=1e-13))
    except ValueError as exc:
        raise ValueError("could not bracket a yield for the supplied price") from exc


def jgb_like_zero_curve(maturities: ArrayLike) -> FloatArray:
    """A deterministic, positive synthetic spot curve in decimal units."""

    tenor = np.asarray(maturities, dtype=float)
    if not np.all(np.isfinite(tenor)) or np.any(tenor < 0.0):
        raise ValueError("maturities must be finite and non-negative")
    return 0.0015 + 0.014 * (1.0 - np.exp(-tenor / 9.0))


@dataclass(frozen=True)
class CouponBondUniverse:
    """Bond-level observations and their long-form contractual cash flows."""

    bonds: pd.DataFrame
    cashflows: pd.DataFrame


def make_synthetic_jgb_universe(
    *,
    maturities: Sequence[float] | None = None,
    coupon_rates: Sequence[float] | None = None,
    frequency: int = 2,
    face_value: float = 100.0,
    zero_curve: ZeroCurve | None = None,
    price_noise_std: float = 0.0,
    seed: Seed = 0,
) -> CouponBondUniverse:
    """Generate a small JGB-like coupon-bond cross-section without downloads.

    ``dirty_price`` is generated from the entire zero curve.  The reported
    ``yield_to_maturity`` is then solved from that price using one scalar
    discount rate, while ``zero_rate_at_maturity`` is the terminal spot rate.
    Keeping both columns makes their conceptual difference explicit.
    """

    frequency = _frequency(frequency)
    if not np.isfinite(face_value) or face_value <= 0.0:
        raise ValueError("face_value must be finite and strictly positive")
    if not np.isfinite(price_noise_std) or price_noise_std < 0.0:
        raise ValueError("price_noise_std must be a finite non-negative number")
    tenor = np.asarray(
        (0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0, 15.0, 20.0, 30.0)
        if maturities is None
        else maturities,
        dtype=float,
    )
    if tenor.ndim != 1 or tenor.size == 0:
        raise ValueError("maturities must be a non-empty vector")
    if not np.all(np.isfinite(tenor)) or np.any(tenor <= 0.0):
        raise ValueError("maturities must be finite and strictly positive")
    if np.any(np.diff(tenor) <= 0.0):
        raise ValueError("maturities must be strictly increasing")
    curve = jgb_like_zero_curve if zero_curve is None else zero_curve
    if not callable(curve):
        raise TypeError("zero_curve must be callable")

    generator = seed if isinstance(seed, Generator) else np.random.default_rng(seed)
    terminal_zero_rates = np.asarray(curve(tenor), dtype=float)
    if terminal_zero_rates.ndim == 0:
        terminal_zero_rates = np.full_like(tenor, float(terminal_zero_rates))
    if terminal_zero_rates.shape != tenor.shape or not np.all(np.isfinite(terminal_zero_rates)):
        raise ValueError("zero_curve must return one finite rate per maturity")
    if coupon_rates is None:
        coupon = np.maximum(
            0.0005,
            np.round((terminal_zero_rates + generator.normal(0.0, 0.001, tenor.size)) * 2000)
            / 2000,
        )
    else:
        coupon = np.asarray(coupon_rates, dtype=float)
        if coupon.shape != tenor.shape:
            raise ValueError("coupon_rates must have one value per maturity")
        if not np.all(np.isfinite(coupon)) or np.any(coupon < 0.0):
            raise ValueError("coupon_rates must be finite and non-negative")

    bond_rows: list[dict[str, float | str | int]] = []
    cashflow_rows: list[dict[str, float | str]] = []
    for index, (maturity, coupon_rate, terminal_rate) in enumerate(
        zip(tenor, coupon, terminal_zero_rates, strict=True), start=1
    ):
        bond_id = f"JGB-SYN-{index:03d}"
        payment_times, payment_amounts = coupon_bond_cashflows(
            float(maturity),
            float(coupon_rate),
            frequency=frequency,
            face_value=face_value,
        )
        dirty_price = price_coupon_bond(
            payment_times,
            payment_amounts,
            curve,
            compounding="continuous",
            frequency=frequency,
        ) + float(generator.normal(0.0, price_noise_std))
        if dirty_price <= 0.0:
            raise ValueError("price noise produced a non-positive dirty price")
        ytm = yield_to_maturity(
            dirty_price,
            payment_times,
            payment_amounts,
            compounding="continuous",
            frequency=frequency,
        )
        bond_rows.append(
            {
                "bond_id": bond_id,
                "maturity_years": float(maturity),
                "coupon_rate": float(coupon_rate),
                "frequency": frequency,
                "face_value": float(face_value),
                "dirty_price": dirty_price,
                "yield_to_maturity": ytm,
                "yield_compounding": "continuous",
                "zero_rate_at_maturity": float(terminal_rate),
            }
        )
        cashflow_rows.extend(
            {
                "bond_id": bond_id,
                "payment_time": float(payment_time),
                "cashflow": float(payment_amount),
            }
            for payment_time, payment_amount in zip(payment_times, payment_amounts, strict=True)
        )

    return CouponBondUniverse(
        bonds=pd.DataFrame.from_records(bond_rows),
        cashflows=pd.DataFrame.from_records(cashflow_rows),
    )


@dataclass(frozen=True)
class BondPriceCurveDiagnostics:
    """Identification and fit diagnostics for a price-space calibration.

    ``rank`` and ``condition_number`` are computed from the weighted
    bond-price Jacobian, excluding the ridge rows.  The two RMSE values are
    always reported in price units.
    """

    rank: int
    condition_number: float
    rmse: float
    weighted_rmse: float
    success: bool
    nfev: int


@dataclass(frozen=True)
class BondPriceCurveFit:
    """A zero curve calibrated to dirty coupon-bond prices."""

    basis_spec: CurveBasisSpec
    coefficients: FloatArray
    bond_ids: tuple[str, ...]
    observed_prices: FloatArray
    fitted_prices: FloatArray
    weights: FloatArray | None
    diagnostics: BondPriceCurveDiagnostics

    @property
    def basis(self) -> str:
        """Canonical curve basis name."""

        return self.basis_spec.basis

    @property
    def decay(self) -> float:
        """Fixed Nelson--Siegel decay stored with the fitted basis."""

        return self.basis_spec.decay

    @property
    def residuals(self) -> FloatArray:
        """Observed minus fitted dirty prices."""

        return self.observed_prices - self.fitted_prices

    def predict_zero_rates(self, maturities: ArrayLike) -> FloatArray:
        """Evaluate the calibrated continuously compounded zero curve."""

        tenor = np.asarray(maturities, dtype=float)
        if tenor.ndim != 1 or tenor.size == 0:
            raise ValueError("maturities must be a non-empty one-dimensional array")
        if not np.all(np.isfinite(tenor)) or np.any(tenor < 0.0):
            raise ValueError("maturities must be finite and non-negative")
        return _basis_matrix(tenor, self.basis_spec) @ self.coefficients


@dataclass(frozen=True)
class _ValidatedBondUniverse:
    bond_ids: tuple[str, ...]
    maturities: FloatArray
    prices: FloatArray
    payment_times: tuple[FloatArray, ...]
    cashflows: tuple[FloatArray, ...]


def _numeric_column(frame: pd.DataFrame, column: str) -> FloatArray:
    try:
        values = np.asarray(frame[column], dtype=float)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{column} must contain numeric values") from exc
    if values.ndim != 1 or not np.all(np.isfinite(values)):
        raise ValueError(f"{column} must contain only finite values")
    return values


def _validated_bond_universe(universe: CouponBondUniverse) -> _ValidatedBondUniverse:
    if not isinstance(universe, CouponBondUniverse):
        raise TypeError("universe must be a CouponBondUniverse")
    if not isinstance(universe.bonds, pd.DataFrame) or not isinstance(
        universe.cashflows, pd.DataFrame
    ):
        raise TypeError("universe bonds and cashflows must be pandas DataFrames")

    required_bond_columns = {"bond_id", "maturity_years", "dirty_price"}
    required_cashflow_columns = {"bond_id", "payment_time", "cashflow"}
    missing_bond_columns = required_bond_columns.difference(universe.bonds.columns)
    missing_cashflow_columns = required_cashflow_columns.difference(universe.cashflows.columns)
    if missing_bond_columns:
        raise ValueError(f"bonds is missing required columns: {sorted(missing_bond_columns)}")
    if missing_cashflow_columns:
        raise ValueError(
            f"cashflows is missing required columns: {sorted(missing_cashflow_columns)}"
        )
    if universe.bonds.empty:
        raise ValueError("universe must contain at least one bond")

    raw_bond_ids = universe.bonds["bond_id"].tolist()
    if any(not isinstance(value, str) or not value for value in raw_bond_ids):
        raise ValueError("bond_id values must be non-empty strings")
    if len(set(raw_bond_ids)) != len(raw_bond_ids):
        raise ValueError("bond_id values must be unique in bonds")
    bond_ids = tuple(raw_bond_ids)

    maturities = _numeric_column(universe.bonds, "maturity_years")
    if np.any(maturities <= 0.0):
        raise ValueError("maturity_years must be strictly positive")
    prices = _numeric_column(universe.bonds, "dirty_price")
    if np.any(prices <= 0.0):
        raise ValueError("dirty_price values must be strictly positive")

    raw_cashflow_ids = universe.cashflows["bond_id"].tolist()
    if any(not isinstance(value, str) or not value for value in raw_cashflow_ids):
        raise ValueError("cashflow bond_id values must be non-empty strings")
    unknown_ids = set(raw_cashflow_ids).difference(bond_ids)
    if unknown_ids:
        raise ValueError(f"cashflows contains unknown bond_id values: {sorted(unknown_ids)}")

    payment_times: list[FloatArray] = []
    payment_amounts: list[FloatArray] = []
    for bond_id, maturity in zip(bond_ids, maturities, strict=True):
        rows = universe.cashflows.loc[universe.cashflows["bond_id"] == bond_id].sort_values(
            "payment_time", kind="stable"
        )
        if rows.empty:
            raise ValueError(f"bond {bond_id!r} has no contractual cash flows")
        times = _numeric_column(rows, "payment_time")
        amounts = _numeric_column(rows, "cashflow")
        times, amounts = _cashflow_vectors(times, amounts)
        if not np.isclose(times[-1], maturity, rtol=0.0, atol=1e-10):
            raise ValueError(f"bond {bond_id!r} final cash flow must occur at maturity_years")
        payment_times.append(times)
        payment_amounts.append(amounts)

    return _ValidatedBondUniverse(
        bond_ids=bond_ids,
        maturities=maturities,
        prices=prices,
        payment_times=tuple(payment_times),
        cashflows=tuple(payment_amounts),
    )


def _calibration_weights(weights: ArrayLike | None, number_of_bonds: int) -> FloatArray | None:
    if weights is None:
        return None
    values = np.asarray(weights, dtype=float)
    if values.ndim != 1 or values.shape != (number_of_bonds,):
        raise ValueError("weights must have one value per bond")
    if not np.all(np.isfinite(values)) or np.any(values <= 0.0):
        raise ValueError("weights must be finite and strictly positive")
    return values


def _prices_and_jacobian(
    coefficients: FloatArray,
    data: _ValidatedBondUniverse,
    spec: CurveBasisSpec,
) -> tuple[FloatArray, FloatArray]:
    prices = np.empty(len(data.bond_ids), dtype=float)
    jacobian = np.empty((len(data.bond_ids), coefficients.size), dtype=float)
    for row, (times, amounts) in enumerate(zip(data.payment_times, data.cashflows, strict=True)):
        basis = _basis_matrix(times, spec)
        zero_rates = basis @ coefficients
        discount = np.exp(-times * zero_rates)
        discounted_cashflows = amounts * discount
        prices[row] = discounted_cashflows.sum()
        jacobian[row] = -(discounted_cashflows * times) @ basis
    return prices, jacobian


def _default_initial_coefficients(data: _ValidatedBondUniverse, spec: CurveBasisSpec) -> FloatArray:
    yields = np.asarray(
        [
            yield_to_maturity(
                price,
                times,
                amounts,
                compounding="continuous",
            )
            for price, times, amounts in zip(
                data.prices, data.payment_times, data.cashflows, strict=True
            )
        ],
        dtype=float,
    )
    return np.linalg.lstsq(_basis_matrix(data.maturities, spec), yields, rcond=None)[0]


def _initial_coefficients(
    initial: ArrayLike | None,
    data: _ValidatedBondUniverse,
    spec: CurveBasisSpec,
) -> FloatArray:
    number_of_coefficients = _basis_matrix(data.maturities, spec).shape[1]
    if initial is None:
        return _default_initial_coefficients(data, spec)
    values = np.asarray(initial, dtype=float)
    if values.ndim != 1 or values.shape != (number_of_coefficients,):
        raise ValueError(f"initial must contain {number_of_coefficients} coefficients")
    if not np.all(np.isfinite(values)):
        raise ValueError("initial must contain only finite values")
    return values


def _positive_integer_or_none(value: int | None, *, name: str) -> int | None:
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, (int, np.integer)):
        raise TypeError(f"{name} must be an integer or None")
    if value <= 0:
        raise ValueError(f"{name} must be strictly positive")
    return int(value)


def fit_bond_price_curve(
    universe: CouponBondUniverse,
    *,
    basis: str = "nelson_siegel",
    degree: int = 3,
    knots: Sequence[float] = (),
    decay: float = 0.5,
    weights: ArrayLike | None = None,
    ridge: float = 0.0,
    initial: ArrayLike | None = None,
    max_nfev: int | None = 2_000,
) -> BondPriceCurveFit:
    r"""Calibrate a fixed-basis zero curve directly to dirty bond prices.

    Every contractual cash flow is discounted with
    :math:`\exp(-t z(t))`; consequently, the fitted coefficients describe
    continuously compounded zero rates, not bond yields to maturity.
    ``weights`` enter the nonlinear least-squares objective as bond-level
    precision weights.  Ridge regularization penalizes the coefficient vector.
    """

    data = _validated_bond_universe(universe)
    spec = _curve_spec(
        data.maturities,
        basis=basis,
        degree=degree,
        knots=knots,
        decay=decay,
    )
    fit_weights = _calibration_weights(weights, len(data.bond_ids))
    square_root_weights = (
        np.ones(len(data.bond_ids), dtype=float) if fit_weights is None else np.sqrt(fit_weights)
    )
    if not np.isfinite(ridge) or ridge < 0.0:
        raise ValueError("ridge must be finite and non-negative")
    evaluation_limit = _positive_integer_or_none(max_nfev, name="max_nfev")
    starting_values = _initial_coefficients(initial, data, spec)
    square_root_ridge = float(np.sqrt(ridge))

    def residuals(coefficients: FloatArray) -> FloatArray:
        fitted_prices, _ = _prices_and_jacobian(coefficients, data, spec)
        price_residuals = square_root_weights * (fitted_prices - data.prices)
        if ridge == 0.0:
            return price_residuals
        return np.concatenate((price_residuals, square_root_ridge * coefficients))

    def residual_jacobian(coefficients: FloatArray) -> FloatArray:
        _, price_jacobian = _prices_and_jacobian(coefficients, data, spec)
        weighted_jacobian = square_root_weights[:, None] * price_jacobian
        if ridge == 0.0:
            return weighted_jacobian
        ridge_jacobian = square_root_ridge * np.eye(coefficients.size)
        return np.vstack((weighted_jacobian, ridge_jacobian))

    result = least_squares(
        residuals,
        starting_values,
        jac=residual_jacobian,
        max_nfev=evaluation_limit,
    )
    coefficients = np.asarray(result.x, dtype=float)
    fitted_prices, price_jacobian = _prices_and_jacobian(coefficients, data, spec)
    weighted_price_jacobian = square_root_weights[:, None] * price_jacobian
    rank = int(np.linalg.matrix_rank(weighted_price_jacobian))
    condition_number = (
        float(np.linalg.cond(weighted_price_jacobian))
        if rank == coefficients.size
        else float("inf")
    )
    squared_errors = (data.prices - fitted_prices) ** 2
    price_rmse = float(np.sqrt(np.mean(squared_errors)))
    price_weighted_rmse = float(np.sqrt(np.average(squared_errors, weights=square_root_weights**2)))
    diagnostics = BondPriceCurveDiagnostics(
        rank=rank,
        condition_number=condition_number,
        rmse=price_rmse,
        weighted_rmse=price_weighted_rmse,
        success=bool(result.success),
        nfev=int(result.nfev),
    )
    return BondPriceCurveFit(
        basis_spec=spec,
        coefficients=coefficients,
        bond_ids=data.bond_ids,
        observed_prices=data.prices.copy(),
        fitted_prices=fitted_prices,
        weights=None if fit_weights is None else fit_weights.copy(),
        diagnostics=diagnostics,
    )


def predict_bond_prices(model: BondPriceCurveFit, universe: CouponBondUniverse) -> FloatArray:
    """Price every bond in ``universe`` from a calibrated zero curve."""

    if not isinstance(model, BondPriceCurveFit):
        raise TypeError("model must be a BondPriceCurveFit")
    data = _validated_bond_universe(universe)
    prices, _ = _prices_and_jacobian(model.coefficients, data, model.basis_spec)
    return prices


def leave_one_bond_out_price_rmse(
    universe: CouponBondUniverse,
    *,
    basis: str = "nelson_siegel",
    degree: int = 3,
    knots: Sequence[float] = (),
    decay: float = 0.5,
    weights: ArrayLike | None = None,
    ridge: float = 0.0,
    initial: ArrayLike | None = None,
    max_nfev: int | None = 2_000,
) -> float:
    """Return leave-one-bond-out price RMSE, weighted when requested."""

    data = _validated_bond_universe(universe)
    if len(data.bond_ids) < 4:
        raise ValueError("leave-one-bond-out validation requires at least four bonds")
    all_weights = _calibration_weights(weights, len(data.bond_ids))
    predictions = np.empty(len(data.bond_ids), dtype=float)

    for held_out, bond_id in enumerate(data.bond_ids):
        training_ids = set(data.bond_ids)
        training_ids.remove(bond_id)
        training_universe = CouponBondUniverse(
            bonds=universe.bonds.loc[universe.bonds["bond_id"].isin(training_ids)].copy(),
            cashflows=universe.cashflows.loc[
                universe.cashflows["bond_id"].isin(training_ids)
            ].copy(),
        )
        training_weights = None if all_weights is None else np.delete(all_weights, held_out)
        model = fit_bond_price_curve(
            training_universe,
            basis=basis,
            degree=degree,
            knots=knots,
            decay=decay,
            weights=training_weights,
            ridge=ridge,
            initial=initial,
            max_nfev=max_nfev,
        )
        held_out_universe = CouponBondUniverse(
            bonds=universe.bonds.loc[universe.bonds["bond_id"] == bond_id].copy(),
            cashflows=universe.cashflows.loc[universe.cashflows["bond_id"] == bond_id].copy(),
        )
        predictions[held_out] = predict_bond_prices(model, held_out_universe)[0]

    squared_errors = (data.prices - predictions) ** 2
    if all_weights is None:
        return float(np.sqrt(np.mean(squared_errors)))
    return float(np.sqrt(np.average(squared_errors, weights=all_weights)))
