"""Manually reviewed semantic claims for the JohnHull Gold paper set."""

from __future__ import annotations

import json
from typing import Any

from .gold import GOLD_ROOT

DEFAULT_CLAIM_SPECS_OUTPUT = GOLD_ROOT / "gold_claim_specs.jsonl"
DEFAULT_CLAIM_METRICS_OUTPUT = GOLD_ROOT / "gold_claim_metrics.json"
GOLD_CLAIM_REVIEWER = "codex-source-claim-audit-2026-07-23"


def _claim(
    paper_id: str,
    key: str,
    claim_type: str,
    statement: str,
    evidence_block_ids: tuple[str, ...],
    *,
    equation_assertion_ids: tuple[str, ...] = (),
    table_ids: tuple[str, ...] = (),
    finance_tags: tuple[str, ...] = (),
    manual_source_excerpts: tuple[str, ...] = (),
) -> dict[str, Any]:
    return {
        "claim_id": f"{paper_id}:claim:{key}",
        "paper_id": paper_id,
        "claim_type": claim_type,
        "statement": statement,
        "evidence_block_ids": evidence_block_ids,
        "equation_assertion_ids": equation_assertion_ids,
        "table_ids": table_ids,
        "finance_tags": finance_tags,
        "manual_source_excerpts": manual_source_excerpts,
        "verification_status": "verified",
        "reviewer": GOLD_CLAIM_REVIEWER,
        "source_review_status": "manual_page_review_pass",
    }


GOLD_CLAIM_SPECS = (
    _claim(
        "1900-bachelier-theorie-de-la-speculation",
        "scope",
        "research_question",
        "The theory applies probability calculus to the principal problems arising in speculation.",
        ("1900-bachelier-theorie-de-la-speculation:p0067:block:0009",),
        finance_tags=("Bachelier", "probability", "speculation"),
    ),
    _claim(
        "1900-bachelier-theorie-de-la-speculation",
        "symmetric-deviations",
        "model_assumption",
        "Price deviations from the true price are assumed independent of the absolute price level and symmetrically distributed.",
        ("1900-bachelier-theorie-de-la-speculation:p0016:block:0003",),
        finance_tags=("true price", "symmetry", "price deviation"),
    ),
    _claim(
        "1900-bachelier-theorie-de-la-speculation",
        "compound-probability",
        "numerical_method",
        "The probability law is derived from the principle of compound probability.",
        ("1900-bachelier-theorie-de-la-speculation:p0016:block:0005",),
        finance_tags=("compound probability", "probability law"),
    ),
    _claim(
        "1900-bachelier-theorie-de-la-speculation",
        "prime-payoff",
        "payoff",
        "The geometric representation of a prime transaction has a linear branch above the exercise threshold and a constant loss below it.",
        ("1900-bachelier-theorie-de-la-speculation:p0011:block:0004",),
        finance_tags=("option payoff", "prime transaction", "constant loss"),
    ),
    _claim(
        "1900-bachelier-theorie-de-la-speculation",
        "observation-warning",
        "limitation",
        "Market observations are presented as illustrations of a probability law rather than as verification of the mathematical formulas.",
        ("1900-bachelier-theorie-de-la-speculation:p0067:block:0010",),
        finance_tags=("empirical validation", "limitation"),
    ),
    _claim(
        "1973-black-scholes-options-corporate-liabilities",
        "no-arbitrage",
        "pricing_equation",
        "Correct option prices preclude sure profits from portfolios of long and short positions in options and their underlying stocks.",
        ("1973-black-scholes-options-corporate-liabilities:p0002:block:0006",),
        finance_tags=("Black-Scholes", "no arbitrage", "replication"),
    ),
    _claim(
        "1973-black-scholes-options-corporate-liabilities",
        "ideal-market",
        "model_assumption",
        "The valuation assumes a known constant short rate, lognormal stock dynamics, no dividends or transaction costs, European exercise, unrestricted borrowing, and short selling.",
        tuple(
            f"1973-black-scholes-options-corporate-liabilities:p0005:block:{ordinal:04d}"
            for ordinal in range(5, 13)
        ),
        finance_tags=("ideal market", "lognormal stock", "European option"),
    ),
    _claim(
        "1973-black-scholes-options-corporate-liabilities",
        "hedged-return",
        "numerical_method",
        "In equilibrium, the expected return on a continuously hedged option-stock position equals the riskless return.",
        ("1973-black-scholes-options-corporate-liabilities:p0005:block:0003",),
        finance_tags=("delta hedge", "riskless return", "equilibrium"),
    ),
    _claim(
        "1973-black-scholes-options-corporate-liabilities",
        "call-boundary",
        "payoff",
        "At maturity, the European call is worth the stock price less the exercise price when positive and otherwise has zero value.",
        (
            "1973-black-scholes-options-corporate-liabilities:p0008:block:0006",
            "1973-black-scholes-options-corporate-liabilities:p0008:block:0007",
        ),
        finance_tags=("European call", "terminal payoff", "boundary condition"),
    ),
    _claim(
        "1973-black-scholes-options-corporate-liabilities",
        "corporate-liabilities",
        "empirical_result",
        "The option-pricing analysis extends to corporate liabilities such as equity, bonds, and warrants.",
        ("1973-black-scholes-options-corporate-liabilities:p0002:block:0006",),
        finance_tags=("corporate liabilities", "default discount", "warrants"),
    ),
    _claim(
        "1990-hull-white-interest-rate-derivative-securities",
        "curve-fit",
        "research_question",
        "The extended short-rate model is designed to fit the current term structure and observed spot or forward-rate volatilities.",
        ("1990-hull-white-interest-rate-derivative-securities:p0001:block:0003",),
        finance_tags=("Hull-White", "term structure", "volatility fit"),
    ),
    _claim(
        "1990-hull-white-interest-rate-derivative-securities",
        "short-rate-dynamics",
        "state_dynamics",
        "The short-rate process permits time-dependent drift, mean reversion, and volatility coefficients.",
        ("1990-hull-white-interest-rate-derivative-securities:p0004:block:0003",),
        equation_assertion_ids=("hw-p4-short-rate-dynamics",),
        finance_tags=("Hull-White", "short rate", "mean reversion"),
    ),
    _claim(
        "1990-hull-white-interest-rate-derivative-securities",
        "bond-loading",
        "pricing_equation",
        "With constant mean reversion, the zero-coupon bond loading is the exponentially decaying Hull-White function.",
        (
            "1990-hull-white-interest-rate-derivative-securities:p0006:block:0001",
            "1990-hull-white-interest-rate-derivative-securities:p0006:block:0002",
        ),
        equation_assertion_ids=("hw-p6-vasicek-b",),
        finance_tags=("Hull-White", "zero-coupon bond", "bond loading"),
    ),
    _claim(
        "1990-hull-white-interest-rate-derivative-securities",
        "calibration",
        "calibration_input",
        "The model parameters are selected to reproduce the initial term structure together with spot-rate or forward-rate volatility information.",
        ("1990-hull-white-interest-rate-derivative-securities:p0006:block:0003",),
        finance_tags=("calibration", "yield curve", "forward volatility"),
    ),
    _claim(
        "1990-hull-white-interest-rate-derivative-securities",
        "analytic-approximation",
        "empirical_result",
        "The extended Vasicek construction provides a practical analytic approximation for interest-rate derivative valuation.",
        ("1990-hull-white-interest-rate-derivative-securities:p0017:block:0003",),
        equation_assertion_ids=(
            "hw-p7-zcb-call",
            "hw-p7-zcb-call-d1",
            "hw-p7-zcb-call-total-variance",
        ),
        finance_tags=("extended Vasicek", "analytic approximation", "bond option"),
    ),
    _claim(
        "1993-heston-closed-form-stochastic-volatility",
        "closed-form",
        "research_question",
        "The model derives a closed-form option-pricing solution with stochastic volatility and arbitrary correlation between returns and volatility.",
        ("1993-heston-closed-form-stochastic-volatility:p0001:block:0003",),
        finance_tags=("Heston", "closed form", "stochastic volatility"),
    ),
    _claim(
        "1993-heston-closed-form-stochastic-volatility",
        "variance-process",
        "state_dynamics",
        "Instantaneous variance follows a square-root process correlated with the asset return innovation.",
        (
            "1993-heston-closed-form-stochastic-volatility:p0002:block:0004",
            "1993-heston-closed-form-stochastic-volatility:p0003:block:0002",
            "1993-heston-closed-form-stochastic-volatility:p0003:block:0004",
        ),
        equation_assertion_ids=(
            "heston-p2-asset-dynamics",
            "heston-p3-variance-dynamics",
        ),
        finance_tags=("Heston", "square-root variance", "correlation"),
    ),
    _claim(
        "1993-heston-closed-form-stochastic-volatility",
        "volatility-risk-premium",
        "model_assumption",
        "Completing the pricing model requires an assumption about the volatility risk premium.",
        (
            "1993-heston-closed-form-stochastic-volatility:p0003:block:0006",
            "1993-heston-closed-form-stochastic-volatility:p0003:block:0008",
        ),
        finance_tags=("volatility risk premium", "market completeness"),
    ),
    _claim(
        "1993-heston-closed-form-stochastic-volatility",
        "characteristic-function",
        "numerical_method",
        "The pricing solution is constructed through the characteristic function, including the reviewed auxiliary quantities g and d.",
        (
            "1993-heston-closed-form-stochastic-volatility:p0005:block:0004",
            "1993-heston-closed-form-stochastic-volatility:p0005:block:0006",
            "1993-heston-closed-form-stochastic-volatility:p0005:block:0010",
            "1993-heston-closed-form-stochastic-volatility:p0005:block:0012",
        ),
        equation_assertion_ids=("heston-p5-g", "heston-p5-d"),
        finance_tags=("characteristic function", "Fourier pricing", "Heston"),
    ),
    _claim(
        "1993-heston-closed-form-stochastic-volatility",
        "correlation-skew",
        "empirical_result",
        "Return-volatility correlation helps explain skewness and strike-dependent option-price bias.",
        ("1993-heston-closed-form-stochastic-volatility:p0001:block:0003",),
        finance_tags=("volatility skew", "leverage effect", "correlation"),
    ),
    _claim(
        "2000-mcneil-frey-tail-risk-evt",
        "two-stage-method",
        "research_question",
        "The proposed tail-risk method combines volatility filtering by pseudo maximum likelihood with extreme value theory for standardized residuals.",
        ("2000-mcneil-frey-tail-risk-evt:p0001:block:0006",),
        finance_tags=("VaR", "expected shortfall", "GARCH", "EVT"),
    ),
    _claim(
        "2000-mcneil-frey-tail-risk-evt",
        "conditional-risk",
        "research_question",
        "The analysis targets conditional quantiles and expected shortfall for heteroscedastic financial return series.",
        ("2000-mcneil-frey-tail-risk-evt:p0005:block:0003",),
        finance_tags=("conditional VaR", "expected shortfall", "heteroscedasticity"),
    ),
    _claim(
        "2000-mcneil-frey-tail-risk-evt",
        "es-location-scale",
        "pricing_equation",
        "Conditional expected shortfall inherits the location-scale form of the filtered return model.",
        (
            "2000-mcneil-frey-tail-risk-evt:p0014:block:0002",
            "2000-mcneil-frey-tail-risk-evt:p0014:block:0003",
        ),
        equation_assertion_ids=("mcneil-frey-p14-es",),
        finance_tags=("expected shortfall", "location scale", "tail conditional mean"),
    ),
    _claim(
        "2000-mcneil-frey-tail-risk-evt",
        "gpd-tail",
        "numerical_method",
        "Threshold exceedances are modeled with a generalized Pareto distribution to estimate tail risk.",
        (
            "2000-mcneil-frey-tail-risk-evt:p0014:block:0004",
            "2000-mcneil-frey-tail-risk-evt:p0014:block:0006",
        ),
        equation_assertion_ids=(
            "mcneil-frey-p8-gpd-quantile",
            "mcneil-frey-p14-gpd-mean",
        ),
        finance_tags=("generalized Pareto", "threshold exceedance", "extreme value"),
    ),
    _claim(
        "2000-mcneil-frey-tail-risk-evt",
        "es-backtest",
        "implementation_warning",
        "Expected-shortfall backtesting examines whether exceedance residuals behave as independent observations with zero mean.",
        (
            "2000-mcneil-frey-tail-risk-evt:p0015:block:0005",
            "2000-mcneil-frey-tail-risk-evt:p0015:block:0007",
            "2000-mcneil-frey-tail-risk-evt:p0015:block:0010",
        ),
        finance_tags=("ES backtest", "exceedance residual", "independence"),
    ),
    _claim(
        "2001-longstaff-schwartz-american-options-lsm",
        "regression-continuation",
        "numerical_method",
        "Least-squares Monte Carlo regresses realized discounted continuation cash flows on basis functions of the state variables.",
        ("2001-longstaff-schwartz-american-options-lsm:p0005:block:0001",),
        finance_tags=("LSM", "least squares Monte Carlo", "continuation value"),
    ),
    _claim(
        "2001-longstaff-schwartz-american-options-lsm",
        "exercise-rule",
        "payoff",
        "Early exercise is selected when the immediate exercise value is at least as large as the estimated continuation value.",
        ("2001-longstaff-schwartz-american-options-lsm:p0010:block:0003",),
        finance_tags=("American option", "exercise policy", "continuation value"),
    ),
    _claim(
        "2001-longstaff-schwartz-american-options-lsm",
        "risk-neutral-continuation",
        "measure_and_numeraire",
        "Continuation value is the risk-neutral conditional expectation of discounted future cash flows under the chosen stopping policy.",
        ("2001-longstaff-schwartz-american-options-lsm:p0010:block:0004",),
        finance_tags=("risk-neutral expectation", "optimal stopping", "discounted cash flow"),
    ),
    _claim(
        "2001-longstaff-schwartz-american-options-lsm",
        "exercise-grid",
        "model_assumption",
        "A continuous exercise opportunity is approximated by a sufficiently dense discrete exercise grid.",
        ("2001-longstaff-schwartz-american-options-lsm:p0010:block:0002",),
        finance_tags=("exercise grid", "Bermudan approximation"),
    ),
    _claim(
        "2001-longstaff-schwartz-american-options-lsm",
        "finite-difference-comparison",
        "empirical_result",
        "The least-squares estimates are close to finite-difference benchmarks and do not exhibit systematic undervaluation.",
        ("2001-longstaff-schwartz-american-options-lsm:p0020:block:0002",),
        finance_tags=("finite difference", "LSM accuracy", "benchmark"),
    ),
    _claim(
        "2002-hagan-et-al-managing-smile-risk",
        "local-vol-warning",
        "limitation",
        "Local-volatility models predict smile motion opposite to the market and can destabilize delta and vega hedges.",
        ("2002-hagan-et-al-managing-smile-risk:p0001:block:0010",),
        finance_tags=("local volatility", "smile dynamics", "hedging instability"),
    ),
    _claim(
        "2002-hagan-et-al-managing-smile-risk",
        "sabr-dynamics",
        "state_dynamics",
        "Under the forward measure, SABR couples a beta-elastic forward process to lognormal stochastic volatility with correlated Brownian shocks.",
        (
            "2002-hagan-et-al-managing-smile-risk:p0008:block:0003",
            "2002-hagan-et-al-managing-smile-risk:p0008:block:0005",
            "2002-hagan-et-al-managing-smile-risk:p0008:block:0006",
            "2002-hagan-et-al-managing-smile-risk:p0008:block:0007",
            "2002-hagan-et-al-managing-smile-risk:p0008:block:0008",
        ),
        equation_assertion_ids=(
            "hagan-p8-sabr-forward-dynamics",
            "hagan-p8-sabr-volatility-dynamics",
            "hagan-p8-sabr-correlation",
        ),
        finance_tags=("SABR", "forward measure", "stochastic volatility", "correlation"),
    ),
    _claim(
        "2002-hagan-et-al-managing-smile-risk",
        "singular-perturbation",
        "numerical_method",
        "Singular perturbation techniques produce an explicit algebraic implied-volatility approximation for European options.",
        ("2002-hagan-et-al-managing-smile-risk:p0001:block:0011",),
        equation_assertion_ids=(
            "hagan-p9-sabr-implied-volatility",
            "hagan-p9-sabr-z",
            "hagan-p9-sabr-xz",
        ),
        finance_tags=("SABR", "singular perturbation", "implied volatility"),
    ),
    _claim(
        "2002-hagan-et-al-managing-smile-risk",
        "calibration",
        "calibration_input",
        "SABR calibration fixes beta and fits correlation, volatility of volatility, and either initial volatility or at-the-money volatility.",
        ("2002-hagan-et-al-managing-smile-risk:p0015:block:0004",),
        finance_tags=("SABR calibration", "beta", "rho", "volvol", "ATM volatility"),
    ),
    _claim(
        "2002-hagan-et-al-managing-smile-risk",
        "single-expiry-scope",
        "implementation_warning",
        "The basic SABR specification is suited to a single exercise date; multi-expiry volatility surfaces require the dynamic extension.",
        (
            "2002-hagan-et-al-managing-smile-risk:p0008:block:0009",
            "2002-hagan-et-al-managing-smile-risk:p0008:block:0010",
        ),
        finance_tags=("swaption", "caplet", "single expiry", "dynamic SABR"),
    ),
    _claim(
        "2003-jarrow-yildirim-inflation-hjm",
        "foreign-currency-analogy",
        "research_question",
        "The inflation HJM framework treats nominal dollars as domestic currency, real dollars as foreign currency, and the CPI as the spot exchange rate.",
        ("2003-jarrow-yildirim-inflation-hjm:p0003:block:0005",),
        finance_tags=("Jarrow-Yildirim", "inflation HJM", "foreign currency analogy"),
    ),
    _claim(
        "2003-jarrow-yildirim-inflation-hjm",
        "curve-and-factor-fit",
        "calibration_input",
        "Implementation first strips nominal and real zero-coupon curves and then fits a correlated factor model to CPI and both curves.",
        (
            "2003-jarrow-yildirim-inflation-hjm:p0003:block:0006",
            "2003-jarrow-yildirim-inflation-hjm:p0003:block:0007",
        ),
        finance_tags=("nominal curve", "real curve", "CPI calibration", "HJM"),
    ),
    _claim(
        "2003-jarrow-yildirim-inflation-hjm",
        "q-martingales",
        "measure_and_numeraire",
        "Under the nominal money-market numeraire, discounted nominal bonds, CPI-scaled real bonds, and the CPI-scaled real account are Q-martingales.",
        (
            "2003-jarrow-yildirim-inflation-hjm:p0007:block:0005",
            "2003-jarrow-yildirim-inflation-hjm:p0007:block:0006",
        ),
        equation_assertion_ids=("jy-p7-q-martingales",),
        finance_tags=("Q measure", "nominal numeraire", "real bond", "martingale"),
    ),
    _claim(
        "2003-jarrow-yildirim-inflation-hjm",
        "cpi-q-dynamics",
        "state_dynamics",
        "Under Q, CPI drift is the nominal short rate minus the real short rate, with CPI volatility driving the diffusion.",
        (
            "2003-jarrow-yildirim-inflation-hjm:p0008:block:0010",
            "2003-jarrow-yildirim-inflation-hjm:p0009:block:0004",
        ),
        equation_assertion_ids=("jy-p9-cpi-q-dynamics",),
        finance_tags=("CPI dynamics", "nominal rate", "real rate", "risk-neutral drift"),
    ),
    _claim(
        "2003-jarrow-yildirim-inflation-hjm",
        "inflation-risk-premium",
        "implementation_warning",
        "The nominal-real spot-rate difference contains expected inflation together with an inflation risk-premium adjustment.",
        ("2003-jarrow-yildirim-inflation-hjm:p0008:block:0010",),
        finance_tags=("Fisher equation", "inflation risk premium", "nominal real spread"),
    ),
    _claim(
        "2009-canty-seasonally-adjusted-inflation-linked-bonds",
        "bei-seasonality-warning",
        "implementation_warning",
        "Ignoring seasonality and carry can materially distort conclusions drawn from inflation-linked bond breakeven rates.",
        (
            "2009-canty-seasonally-adjusted-inflation-linked-bonds:p0001:block:0002",
            "2009-canty-seasonally-adjusted-inflation-linked-bonds:p0001:block:0004",
        ),
        finance_tags=("breakeven inflation", "seasonality", "carry"),
    ),
    _claim(
        "2009-canty-seasonally-adjusted-inflation-linked-bonds",
        "multiplicative-seasonality",
        "state_dynamics",
        "The inflation index is decomposed multiplicatively into a trend component and a seasonal component.",
        (
            "2009-canty-seasonally-adjusted-inflation-linked-bonds:p0002:block:0016",
            "2009-canty-seasonally-adjusted-inflation-linked-bonds:p0002:block:0017",
            "2009-canty-seasonally-adjusted-inflation-linked-bonds:p0002:block:0018",
        ),
        equation_assertion_ids=("canty-p2-seasonality-decomposition",),
        finance_tags=("CPI seasonality", "trend", "multiplicative decomposition"),
    ),
    _claim(
        "2009-canty-seasonally-adjusted-inflation-linked-bonds",
        "seasonally-adjusted-price",
        "pricing_equation",
        "The seasonally adjusted clean price is obtained from the quoted clean price using the settlement-to-maturity seasonal-factor ratio, with an accrued-interest correction.",
        (
            "2009-canty-seasonally-adjusted-inflation-linked-bonds:p0003:block:0026",
            "2009-canty-seasonally-adjusted-inflation-linked-bonds:p0003:block:0028",
        ),
        finance_tags=("seasonally adjusted clean price", "seasonal factor", "accrued interest"),
    ),
    _claim(
        "2009-canty-seasonally-adjusted-inflation-linked-bonds",
        "repeating-monthly-factors",
        "model_assumption",
        "Seasonal factors are assumed constant through time and generated by repeating one annual set of monthly factors.",
        ("2009-canty-seasonally-adjusted-inflation-linked-bonds:p0005:block:0013",),
        table_ids=("2009-canty-seasonally-adjusted-inflation-linked-bonds:p0005:table:0001",),
        finance_tags=("monthly seasonal factors", "constant seasonality", "annual cycle"),
    ),
    _claim(
        "2009-canty-seasonally-adjusted-inflation-linked-bonds",
        "lagged-interpolation",
        "implementation_warning",
        "Inflation-linked bond indices commonly use lagged monthly observations with linear interpolation, so seasonal adjustment must follow the instrument convention.",
        (
            "2009-canty-seasonally-adjusted-inflation-linked-bonds:p0005:block:0017",
            "2009-canty-seasonally-adjusted-inflation-linked-bonds:p0005:block:0019",
        ),
        finance_tags=("index lag", "linear interpolation", "inflation-linked bond"),
    ),
    _claim(
        "2013-wu-inflation-rate-derivatives",
        "market-model",
        "research_question",
        "The inflation market model is built from risk-neutral dynamics of nominal and real zero-coupon bonds and supports caplet and swaption pricing.",
        ("2013-wu-inflation-rate-derivatives:p0002:block:0002",),
        finance_tags=("inflation market model", "nominal bond", "real bond"),
    ),
    _claim(
        "2013-wu-inflation-rate-derivatives",
        "foreign-currency-analogy",
        "model_assumption",
        "The foreign-currency analogy maps nominal rates to domestic rates, real rates to foreign rates, and CPI to the exchange rate.",
        ("2013-wu-inflation-rate-derivatives:p0003:block:0002",),
        finance_tags=("foreign currency analogy", "CPI", "nominal real rates"),
    ),
    _claim(
        "2013-wu-inflation-rate-derivatives",
        "zciis-payoff",
        "payoff",
        "A zero-coupon inflation swap exchanges realized cumulative inflation against a fixed compounded payment at maturity.",
        (
            "2013-wu-inflation-rate-derivatives:p0007:block:0007",
            "2013-wu-inflation-rate-derivatives:p0007:block:0009",
            "2013-wu-inflation-rate-derivatives:p0007:block:0010",
        ),
        equation_assertion_ids=("wu-p7-zciis-fixed-payoff",),
        finance_tags=("ZCIIS", "inflation swap", "fixed payoff"),
    ),
    _claim(
        "2013-wu-inflation-rate-derivatives",
        "fisher-relation",
        "pricing_equation",
        "The Fisher relation decomposes the nominal short rate into the real short rate and instantaneous inflation.",
        (
            "2013-wu-inflation-rate-derivatives:p0008:block:0008",
            "2013-wu-inflation-rate-derivatives:p0008:block:0009",
        ),
        equation_assertion_ids=("wu-p8-fisher-relation",),
        finance_tags=("Fisher relation", "nominal rate", "real rate", "inflation rate"),
    ),
    _claim(
        "2013-wu-inflation-rate-derivatives",
        "forward-measure",
        "measure_and_numeraire",
        "A tradable forward inflation quantity is a martingale under its maturity forward measure, whose density uses the nominal discount bond as numeraire.",
        (
            "2013-wu-inflation-rate-derivatives:p0014:block:0002",
            "2013-wu-inflation-rate-derivatives:p0014:block:0004",
            "2013-wu-inflation-rate-derivatives:p0014:block:0005",
        ),
        equation_assertion_ids=("wu-p14-forward-measure-density",),
        finance_tags=("forward measure", "numeraire", "Radon-Nikodym", "inflation forward"),
    ),
    _claim(
        "2019-lyashenko-mercurio-backward-looking-rates",
        "unified-rates",
        "research_question",
        "The classic rate framework is extended to model forward-looking and backward-looking term rates with the same stochastic process.",
        ("2019-lyashenko-mercurio-backward-looking-rates:p0001:block:0005",),
        finance_tags=("RFR", "backward-looking rate", "forward-looking rate", "FMM"),
    ),
    _claim(
        "2019-lyashenko-mercurio-backward-looking-rates",
        "risk-neutral-numeraire",
        "measure_and_numeraire",
        "Risk-neutral valuation uses the money-market account as numeraire and discounts the short rate inside the bond-price expectation.",
        (
            "2019-lyashenko-mercurio-backward-looking-rates:p0004:block:0001",
            "2019-lyashenko-mercurio-backward-looking-rates:p0004:block:0002",
        ),
        equation_assertion_ids=("lyashenko-p4-risk-neutral-bond-price",),
        finance_tags=("risk-neutral measure", "money-market numeraire", "discount bond"),
    ),
    _claim(
        "2019-lyashenko-mercurio-backward-looking-rates",
        "extended-forward-measure",
        "measure_and_numeraire",
        "After maturity the reinvested bond proceeds remain a positive self-financing numeraire, extending the forward measure beyond maturity.",
        (
            "2019-lyashenko-mercurio-backward-looking-rates:p0004:block:0008",
            "2019-lyashenko-mercurio-backward-looking-rates:p0004:block:0010",
            "2019-lyashenko-mercurio-backward-looking-rates:p0004:block:0012",
        ),
        equation_assertion_ids=("lyashenko-p4-bond-after-maturity",),
        finance_tags=("extended forward measure", "post-maturity numeraire", "self-financing"),
    ),
    _claim(
        "2019-lyashenko-mercurio-backward-looking-rates",
        "measure-drift-adjustment",
        "implementation_warning",
        "The drift difference between the money-market measure and the discrete rolling measure is explicit and quantifies the measure approximation.",
        (
            "2019-lyashenko-mercurio-backward-looking-rates:p0012:block:0010",
            "2019-lyashenko-mercurio-backward-looking-rates:p0012:block:0012",
        ),
        finance_tags=("measure change", "drift adjustment", "rolling numeraire"),
    ),
    _claim(
        "2019-lyashenko-mercurio-backward-looking-rates",
        "analytics-and-implementation",
        "empirical_result",
        "Backward-looking rates retain key martingale and analytic properties while allowing an incremental implementation from the classic market model.",
        (
            "2019-lyashenko-mercurio-backward-looking-rates:p0020:block:0013",
            "2019-lyashenko-mercurio-backward-looking-rates:p0020:block:0014",
        ),
        finance_tags=("backward-looking RFR", "martingale property", "implementation cost"),
    ),
    _claim(
        "2008-fang-oosterlee-cos-method",
        "characteristic-cosine-link",
        "research_question",
        "The COS method exploits the relation between a characteristic function and Fourier-cosine coefficients of the density.",
        ("2008-fang-oosterlee-cos-method:p0001:block:0003",),
        finance_tags=("COS method", "characteristic function", "Fourier cosine"),
    ),
    _claim(
        "2008-fang-oosterlee-cos-method",
        "convergence-complexity",
        "empirical_result",
        "For many models the COS method converges exponentially with linear computational complexity.",
        ("2008-fang-oosterlee-cos-method:p0001:block:0003",),
        finance_tags=("exponential convergence", "linear complexity", "COS method"),
    ),
    _claim(
        "2008-fang-oosterlee-cos-method",
        "calibration-many-strikes",
        "calibration_input",
        "Fast pricing across many strikes is especially important when model prices are evaluated repeatedly inside calibration.",
        ("2008-fang-oosterlee-cos-method:p0001:block:0008",),
        finance_tags=("calibration", "many strikes", "Heston"),
    ),
    _claim(
        "2008-fang-oosterlee-cos-method",
        "fft-limitations",
        "limitation",
        "Standard FFT quadrature has grid and convergence constraints, including power-of-two sizing and a coupled domain grid.",
        (
            "2008-fang-oosterlee-cos-method:p0003:block:0007",
            "2008-fang-oosterlee-cos-method:p0003:block:0009",
        ),
        finance_tags=("FFT", "Nyquist grid", "quadrature limitation"),
    ),
    _claim(
        "2008-fang-oosterlee-cos-method",
        "error-decomposition",
        "numerical_method",
        "COS pricing error is decomposed into integration-range truncation, cosine-series truncation, and characteristic-function coefficient approximation.",
        ("2008-fang-oosterlee-cos-method:p0010:block:0013",),
        finance_tags=("error analysis", "truncation error", "COS method"),
    ),
    _claim(
        "2020-huge-savine-differential-machine-learning",
        "aad-ml-combination",
        "research_question",
        "Differential machine learning combines adjoint differentiation with supervised learning for fast derivative pricing and risk approximations.",
        (
            "2020-huge-savine-differential-machine-learning:p0001:block:0006",
            "2020-huge-savine-differential-machine-learning:p0001:block:0007",
        ),
        finance_tags=("differential ML", "AAD", "pricing surrogate", "risk"),
    ),
    _claim(
        "2020-huge-savine-differential-machine-learning",
        "pathwise-differentials",
        "numerical_method",
        "Adjoint differentiation supplies low-cost pathwise sensitivities that train value and risk as functions of market state.",
        (
            "2020-huge-savine-differential-machine-learning:p0005:block:0002",
            "2020-huge-savine-differential-machine-learning:p0005:block:0003",
        ),
        finance_tags=("pathwise derivative", "AAD", "Greeks"),
    ),
    _claim(
        "2020-huge-savine-differential-machine-learning",
        "simulated-cashflows",
        "model_assumption",
        "Training can use arbitrary cash-flow schedules simulated under arbitrary stochastic models without requiring closed-form prices.",
        ("2020-huge-savine-differential-machine-learning:p0005:block:0007",),
        finance_tags=("simulation", "cash flow", "stochastic model", "XVA"),
    ),
    _claim(
        "2020-huge-savine-differential-machine-learning",
        "differentials-as-data",
        "numerical_method",
        "Differential labels act like data augmentation, reducing variance without introducing the usual bias-variance tradeoff.",
        ("2020-huge-savine-differential-machine-learning:p0010:block:0002",),
        finance_tags=("data augmentation", "differential labels", "variance reduction"),
    ),
    _claim(
        "2020-huge-savine-differential-machine-learning",
        "small-sample-result",
        "empirical_result",
        "Twin networks using differential labels outperform conventional networks on small training sets and approach Monte Carlo accuracy more quickly.",
        (
            "2020-huge-savine-differential-machine-learning:p0010:block:0010",
            "2020-huge-savine-differential-machine-learning:p0010:block:0011",
        ),
        finance_tags=("twin network", "small sample", "Monte Carlo accuracy"),
    ),
    _claim(
        "2021-mof-jgbi-indexation-notice",
        "notional-principal",
        "pricing_equation",
        "各日の想定元金額は、額面金額に各日における連動係数を乗じて算出する。",
        ("2021-mof-jgbi-indexation-notice:p0001:block:0001",),
        finance_tags=("JGBI", "想定元金額", "額面金額", "連動係数"),
        manual_source_excerpts=(
            "第一条 各日における想定元金額は、次の式により算出する。額面金額×各日における連動係数",
        ),
    ),
    _claim(
        "2021-mof-jgbi-indexation-notice",
        "coefficient-regime",
        "implementation_warning",
        "連動係数の算式と端数処理は、発行時期および同一記号での追加発行かどうかに応じて区分される。",
        (
            "2021-mof-jgbi-indexation-notice:p0001:block:0001",
            "2021-mof-jgbi-indexation-notice:p0003:block:0003",
        ),
        finance_tags=("JGBI", "連動係数", "端数処理", "発行時期"),
        manual_source_excerpts=(
            "連動係数は区分に応じた式で算出し、所定の桁未満の端数を四捨五入する。",
            "基準改定前後および発行時期に応じて連動係数の算式を区分する。",
        ),
    ),
    _claim(
        "2021-mof-jgbi-indexation-notice",
        "cpi-definition",
        "calibration_input",
        "告示上の消費者物価指数は、全国消費者物価指数のうち生鮮食品を除く総合指数である。",
        ("2021-mof-jgbi-indexation-notice:p0004:block:0002",),
        finance_tags=("JGBI", "コアCPI", "生鮮食品を除く総合指数"),
        manual_source_excerpts=("全国消費者物価指数のうち生鮮食品を除く総合指数をいう。",),
    ),
    _claim(
        "2021-mof-jgbi-indexation-notice",
        "issue-date-definition",
        "implementation_warning",
        "国債発行日の属する月の基準日は、初期利子期間が短い場合に別の基準へ調整される。",
        ("2021-mof-jgbi-indexation-notice:p0004:block:0003",),
        finance_tags=("JGBI", "国債発行日", "初期利子", "基準日"),
        manual_source_excerpts=(
            "国債発行日から初期利子の支払期までの期間が六月に満たない場合は、当該初期利子の支払期の六月前の日の属する月の十日をいう。",
        ),
    ),
    _claim(
        "2021-mof-jgbi-indexation-notice",
        "reopening-rule",
        "implementation_warning",
        "同一記号で追加発行される物価連動国債は、最初に発行された同一記号債の基準日を引き継ぐ。",
        (
            "2021-mof-jgbi-indexation-notice:p0004:block:0003",
            "2021-mof-jgbi-indexation-notice:p0005:block:0003",
        ),
        finance_tags=("JGBI", "リオープン", "同一記号", "追加発行"),
        manual_source_excerpts=(
            "既に発行されている物価連動国債と同一の記号として発行された場合は、最初に発行された際の国債発行日の属する月の十日を用いる。",
            "同一の記号の物価連動国債について既発債の基準日を適用する。",
        ),
    ),
    _claim(
        "2024-mof-jgbi-bei-guide",
        "bei-definition-bias",
        "implementation_warning",
        "BEIは名目金利と実質金利の差だが、元本保証オプション、流動性、リスク・プレミアムの影響を含む。",
        ("2024-mof-jgbi-bei-guide:p0001:block:0014",),
        finance_tags=("JGBI", "BEI", "名目金利", "実質金利", "バイアス"),
    ),
    _claim(
        "2024-mof-jgbi-bei-guide",
        "principal-floor",
        "payoff",
        "新型物価連動国債の満期元本には額面を下限とするフロアがあり、債券価格にオプション価値が含まれる。",
        (
            "2024-mof-jgbi-bei-guide:p0005:block:0004",
            "2024-mof-jgbi-bei-guide:p0005:block:0005",
        ),
        finance_tags=("JGBI", "元本保証", "デフレフロア", "オプション価値"),
    ),
    _claim(
        "2024-mof-jgbi-bei-guide",
        "floor-coupon-scope",
        "implementation_warning",
        "元本フロアは償還元本に適用されるが、期中クーポンの連動元本には同じ下限が適用されない。",
        ("2024-mof-jgbi-bei-guide:p0007:block:0010",),
        finance_tags=("JGBI", "元本フロア", "クーポン", "償還"),
    ),
    _claim(
        "2024-mof-jgbi-bei-guide",
        "indexation-coefficient",
        "pricing_equation",
        "想定元本は額面金額に連動係数を乗じ、クーポンも連動係数に応じて増減する。",
        (
            "2024-mof-jgbi-bei-guide:p0007:block:0005",
            "2024-mof-jgbi-bei-guide:p0007:block:0007",
        ),
        finance_tags=("JGBI", "想定元本", "連動係数", "クーポン"),
    ),
    _claim(
        "2024-mof-jgbi-bei-guide",
        "lag-and-interpolation",
        "calibration_input",
        "適用指数は公表ラグのあるコアCPIを用い、毎月の基準日を軸に日次値へ線形補間する。",
        (
            "2024-mof-jgbi-bei-guide:p0008:block:0003",
            "2024-mof-jgbi-bei-guide:p0008:block:0004",
            "2024-mof-jgbi-bei-guide:p0009:block:0002",
            "2024-mof-jgbi-bei-guide:p0009:block:0012",
        ),
        finance_tags=("JGBI", "適用指数", "コアCPI", "公表ラグ", "線形補間"),
    ),
)


def render_claim_specs(specs: tuple[dict[str, Any], ...] = GOLD_CLAIM_SPECS) -> str:
    """Serialize the reviewed claim registry deterministically."""

    return "".join(
        json.dumps(item, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
        for item in specs
    )
