/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deals */
        get: operations["list_deals_deals_get"];
        put?: never;
        /** Create Deal */
        post: operations["create_deal_deals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{deal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deal */
        get: operations["get_deal_deals__deal_id__get"];
        put?: never;
        post?: never;
        /** Delete Deal */
        delete: operations["delete_deal_deals__deal_id__delete"];
        options?: never;
        head?: never;
        /** Patch Deal */
        patch: operations["patch_deal_deals__deal_id__patch"];
        trace?: never;
    };
    "/deals/{deal_id}/analysis_runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analysis Runs */
        get: operations["list_analysis_runs_deals__deal_id__analysis_runs_get"];
        put?: never;
        /**
         * Create Analysis Run
         * @description assumptions を受け取り、サーバで full 分析を実行して保存する。
         */
        post: operations["create_analysis_run_deals__deal_id__analysis_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis_runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis Run */
        get: operations["get_analysis_run_analysis_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis_runs/{run_id}/bid_ranges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bid Ranges */
        get: operations["get_bid_ranges_analysis_runs__run_id__bid_ranges_get"];
        put?: never;
        /** Generate Bid Ranges */
        post: operations["generate_bid_ranges_analysis_runs__run_id__bid_ranges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis_runs/{run_id}/assumption_risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assumption Risks */
        get: operations["get_assumption_risks_analysis_runs__run_id__assumption_risks_get"];
        put?: never;
        /** Generate Assumption Risks */
        post: operations["generate_assumption_risks_analysis_runs__run_id__assumption_risks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sample/nishi-shinjuku": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sample Nishi Shinjuku
         * @description デモ物件のサンプル分析 (フロント検証用)。
         */
        get: operations["sample_nishi_shinjuku_sample_nishi_shinjuku_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/max_offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Max Offer */
        post: operations["post_max_offer_max_offer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Sensitivity */
        post: operations["post_sensitivity_sensitivity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cross_asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Cross Asset */
        post: operations["post_cross_asset_cross_asset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Extract Url */
        post: operations["post_extract_url_extract_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Extract Document */
        post: operations["post_extract_document_extract_document_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_analyses_get"];
        put?: never;
        /** Post Save Analysis */
        post: operations["post_save_analysis_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis By Id */
        get: operations["get_analysis_by_id_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/purge-expired-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purge Expired Documents
         * @description delete_after < now() の uploaded_documents を削除。本番では cron で叩く。
         */
        post: operations["purge_expired_documents_admin_purge_expired_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Summarize */
        post: operations["post_summarize_summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/critique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Critique */
        post: operations["post_critique_critique_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcquisitionAssumptions */
        AcquisitionAssumptions: {
            /** Equity Yen */
            equity_yen: number;
            /**
             * Acquisition Cost Rate
             * @default 0.07
             */
            acquisition_cost_rate: number;
        };
        /** AnalysisResult */
        AnalysisResult: {
            /** Engine Version */
            engine_version: string;
            assumptions: components["schemas"]["Assumptions"];
            /** Yearly Cashflows */
            yearly_cashflows: components["schemas"]["YearlyCashflow"][];
            /** Loan Schedule */
            loan_schedule: components["schemas"]["LoanScheduleRow"][];
            exit: components["schemas"]["ExitResult"];
            kpi: components["schemas"]["KPI"];
        };
        /** AnalysisRunOut */
        AnalysisRunOut: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string;
            /** Engine Version */
            engine_version: string;
            /** Prompt Versions */
            prompt_versions: {
                [key: string]: string;
            } | null;
            /** Input Snapshot Json */
            input_snapshot_json: {
                [key: string]: unknown;
            };
            /** Normalized Property Json */
            normalized_property_json: {
                [key: string]: unknown;
            };
            /** Metrics Json */
            metrics_json: {
                [key: string]: unknown;
            };
            /** Sensitivity Json */
            sensitivity_json: {
                [key: string]: unknown;
            } | null;
            /** Max Bid Json */
            max_bid_json: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            assumptions: components["schemas"]["Assumptions"];
            /** Normalized Property */
            normalized_property?: {
                [key: string]: unknown;
            } | null;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            analysis: components["schemas"]["AnalysisResult"];
            assumption_score: components["schemas"]["AssumptionScore"];
        };
        /** AssetBenchmark */
        AssetBenchmark: {
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "real_estate" | "world_equity" | "us_equity" | "japan_equity" | "jreit" | "jp_bonds" | "us_bonds" | "jpy_deposit" | "mmf";
            /** Label Jp */
            label_jp: string;
            /** Expected Return Annual */
            expected_return_annual: number;
            /**
             * Liquidity
             * @enum {string}
             */
            liquidity: "high" | "medium" | "low";
            /**
             * Diversification
             * @enum {string}
             */
            diversification: "high" | "medium" | "low";
            /**
             * Effort
             * @enum {string}
             */
            effort: "high" | "medium" | "low";
            /** Leverage Risk */
            leverage_risk: boolean;
            /** Fx Risk */
            fx_risk: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** AssumptionRisk */
        AssumptionRisk: {
            /**
             * Category
             * @enum {string}
             */
            category: "rent" | "vacancy" | "opex" | "repair" | "interest_rate" | "exit_price" | "tax" | "sale_year" | "acquisition_cost";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "A" | "B" | "C" | "D";
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "low" | "medium" | "high" | "unknown";
            /** Reason */
            reason: string;
            /** Source */
            source?: string | null;
            /** Value Json */
            value_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** AssumptionRiskOut */
        AssumptionRiskOut: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: string;
            /** Risk Level */
            risk_level: string;
            /** Reason */
            reason: string;
            /** Source */
            source: string | null;
            /** Value Json */
            value_json: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string;
        };
        /** AssumptionRisksGenerateRequest */
        AssumptionRisksGenerateRequest: {
            market?: components["schemas"]["MarketBenchmark"] | null;
        };
        /** AssumptionRisksListOut */
        AssumptionRisksListOut: {
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Items */
            items: components["schemas"]["AssumptionRiskOut"][];
            /** Summary */
            summary: string;
        };
        /**
         * AssumptionScore
         * @description 甘さスコア: 物件評価ではなく、分析前提の信頼度と脆弱性の集約。
         */
        AssumptionScore: {
            /**
             * Overall Risk
             * @enum {string}
             */
            overall_risk: "low" | "medium" | "high" | "unknown";
            /** Summary */
            summary: string;
            /** Items */
            items: components["schemas"]["AssumptionRisk"][];
        };
        /** Assumptions */
        Assumptions: {
            /**
             * Engine Version
             * @default 0.1.0
             */
            engine_version: string;
            property: components["schemas"]["PropertyAssumptions"];
            income: components["schemas"]["IncomeAssumptions"];
            opex: components["schemas"]["OpexAssumptions"];
            loan: components["schemas"]["LoanAssumptions"];
            tax?: components["schemas"]["TaxAssumptions"];
            exit?: components["schemas"]["ExitAssumptions"];
            acquisition: components["schemas"]["AcquisitionAssumptions"];
        };
        /** BidRangesGenerateRequest */
        BidRangesGenerateRequest: {
            /** Market */
            market?: {
                [key: string]: unknown;
            } | null;
        };
        /** BidRangesOut */
        BidRangesOut: {
            /** Id */
            id: string;
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Asking Price Yen */
            asking_price_yen: number;
            /** Aggressive Price */
            aggressive_price: number | null;
            /** Base Price */
            base_price: number | null;
            /** Conservative Price */
            conservative_price: number | null;
            /** Gap To Base Price Yen */
            gap_to_base_price_yen: number | null;
            /** Gap To Base Price Pct */
            gap_to_base_price_pct: number | null;
            /** Explanation */
            explanation: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** Body_post_extract_document_extract_document_post */
        Body_post_extract_document_extract_document_post: {
            /** File */
            file: string;
        };
        /** ComparisonRow */
        ComparisonRow: {
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "real_estate" | "world_equity" | "us_equity" | "japan_equity" | "jreit" | "jp_bonds" | "us_bonds" | "jpy_deposit" | "mmf";
            /** Label Jp */
            label_jp: string;
            /** Expected Return */
            expected_return: number;
            /** Premium Over Re Pt */
            premium_over_re_pt: number;
            /**
             * Liquidity
             * @enum {string}
             */
            liquidity: "high" | "medium" | "low";
            /**
             * Effort
             * @enum {string}
             */
            effort: "high" | "medium" | "low";
            /** Note */
            note: string;
        };
        /**
         * CreateAnalysisRunRequest
         * @description 新規分析実行。
         *
         *     assumptions を渡すとサーバ側で run_full_analysis を呼ぶ。
         *     metrics_json などを直接渡したい場合は precomputed=True にする (テスト・移行用)。
         */
        CreateAnalysisRunRequest: {
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            };
            /** Normalized Property */
            normalized_property?: {
                [key: string]: unknown;
            } | null;
            /** Prompt Versions */
            prompt_versions?: {
                [key: string]: string;
            } | null;
            /** Sensitivity Json */
            sensitivity_json?: {
                [key: string]: unknown;
            } | null;
            /** Max Bid Json */
            max_bid_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** CreateDealRequest */
        CreateDealRequest: {
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url?: string | null;
            /** Property Type */
            property_type?: string | null;
            /** Status */
            status?: string | null;
        };
        /** CritiqueItem */
        CritiqueItem: {
            /** Flag Type */
            flag_type: string;
            /** Severity */
            severity: string;
            /** Explanation */
            explanation: string;
            /** Verification */
            verification: string;
        };
        /** CritiqueRequest */
        CritiqueRequest: {
            /** Analysis Result */
            analysis_result: {
                [key: string]: unknown;
            };
            /** Assumption Score */
            assumption_score: {
                [key: string]: unknown;
            };
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            };
        };
        /** CritiqueResponse */
        CritiqueResponse: {
            /** Critiques */
            critiques: components["schemas"]["CritiqueItem"][];
            /** Rule Flags */
            rule_flags?: string[];
            /** Model */
            model: string;
        };
        /** CrossAssetRequest */
        CrossAssetRequest: {
            /** Re After Tax Irr */
            re_after_tax_irr: number | null;
            /** Benchmarks */
            benchmarks?: components["schemas"]["AssetBenchmark"][];
        };
        /** CrossAssetResult */
        CrossAssetResult: {
            /**
             * Re Label Jp
             * @default 本物件 (税後)
             */
            re_label_jp: string;
            /** Re After Tax Irr */
            re_after_tax_irr: number | null;
            /** Rows */
            rows: components["schemas"]["ComparisonRow"][];
            /**
             * Disclaimer
             * @default 資産クラス間の参考シナリオ比較です。特定金融商品の売買を推奨するものではありません。過去データ・仮定に基づく試算であり、将来のリターンを保証するものではありません。最終的な投資判断はユーザー自身の責任で行ってください。
             */
            disclaimer: string;
        };
        /** DealOut */
        DealOut: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string | null;
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url: string | null;
            /** Property Type */
            property_type: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Latest Analysis Run Id */
            latest_analysis_run_id?: string | null;
        };
        /** ExitAssumptions */
        ExitAssumptions: {
            /**
             * Hold Period Years
             * @default 10
             */
            hold_period_years: number;
            /**
             * Exit Cap Rate
             * @default 0.06
             */
            exit_cap_rate: number;
            /**
             * Selling Cost Rate
             * @default 0.04
             */
            selling_cost_rate: number;
        };
        /** ExitResult */
        ExitResult: {
            /** Sale Price Yen */
            sale_price_yen: number;
            /** Selling Costs Yen */
            selling_costs_yen: number;
            /** Remaining Loan Yen */
            remaining_loan_yen: number;
            /** Book Value Yen */
            book_value_yen: number;
            /** Capital Gain Yen */
            capital_gain_yen: number;
            /** Capital Gain Tax Yen */
            capital_gain_tax_yen: number;
            /** Net Proceeds Yen */
            net_proceeds_yen: number;
        };
        /** ExtractUrlRequest */
        ExtractUrlRequest: {
            /** Url */
            url: string;
        };
        /** ExtractionMeta */
        ExtractionMeta: {
            /** Engine Version */
            engine_version: string;
            /** Prompt Versions */
            prompt_versions: {
                [key: string]: string;
            };
            /** Pii Redactions */
            pii_redactions: {
                [key: string]: number;
            };
            /** Classification */
            classification: {
                [key: string]: unknown;
            };
            /** Llm */
            llm: {
                [key: string]: unknown;
            };
            /**
             * Completeness Score
             * @default 0
             */
            completeness_score: number;
            /** Warnings */
            warnings?: string[];
            /** Needs Confirmation */
            needs_confirmation?: string[];
            /** Missing Required */
            missing_required?: string[];
            /** Derived */
            derived?: string[];
        };
        /**
         * ExtractionResponse
         * @description 抽出 API のレスポンス。
         *
         *     - assumptions が None の場合は missing_required を埋めてから /analyze を呼ぶ。
         *     - assumptions が埋まっている場合でも meta.needs_confirmation は確認画面で表示する。
         *     - rent_roll が含まれる場合は rent_roll フィールドに JSON が入る。
         */
        ExtractionResponse: {
            /** Source Type */
            source_type: string;
            /** Source Ref */
            source_ref: string | null;
            extracted: components["schemas"]["PropertyBrochureExtraction"];
            assumptions: components["schemas"]["Assumptions"] | null;
            /** Rent Roll */
            rent_roll?: {
                [key: string]: unknown;
            } | null;
            meta: components["schemas"]["ExtractionMeta"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeAssumptions */
        IncomeAssumptions: {
            /** Gpi Monthly Yen */
            gpi_monthly_yen: number;
            /**
             * Other Income Monthly Yen
             * @default 0
             */
            other_income_monthly_yen: number;
            /**
             * Vacancy Rate
             * @default 0.05
             */
            vacancy_rate: number;
            /**
             * Rent Growth Rate
             * @default -0.005
             */
            rent_growth_rate: number;
            /**
             * Bad Debt Rate
             * @default 0
             */
            bad_debt_rate: number;
        };
        /** InquiryQuestionOut */
        InquiryQuestionOut: {
            /** Category */
            category: string;
            /** Question */
            question: string;
            /** Rationale */
            rationale: string;
        };
        /** InvestorTargets */
        InvestorTargets: {
            /**
             * Min Dscr
             * @default 1.25
             */
            min_dscr: number;
            /**
             * Min Irr
             * @default 0.08
             */
            min_irr: number;
            /**
             * Min First Year Atcf Yen
             * @default 0
             */
            min_first_year_atcf_yen: number;
            /** Max Equity Yen */
            max_equity_yen?: number | null;
            /** Stress Interest Rate */
            stress_interest_rate?: number | null;
        };
        /** KPI */
        KPI: {
            /** Cap Rate */
            cap_rate: number;
            /** Cash On Cash */
            cash_on_cash: number;
            /** Dscr Min */
            dscr_min: number;
            /** Dscr Year1 */
            dscr_year1: number;
            /** Ltv */
            ltv: number;
            /** Equity Irr */
            equity_irr: number | null;
            /** Equity Multiple */
            equity_multiple: number;
            /** Payback Years */
            payback_years: number | null;
            /** Btcf First Year Yen */
            btcf_first_year_yen: number;
            /** Atcf First Year Yen */
            atcf_first_year_yen: number;
            /** Dead Cross Year */
            dead_cross_year?: number | null;
        };
        /** LoanAssumptions */
        LoanAssumptions: {
            /** Loan Amount Yen */
            loan_amount_yen: number;
            /** Interest Rate */
            interest_rate: number;
            /** Term Years */
            term_years: number;
            /**
             * Repayment Type
             * @default amortized
             * @enum {string}
             */
            repayment_type: "amortized" | "principal_equal";
            /**
             * Grace Period Months
             * @default 0
             */
            grace_period_months: number;
        };
        /** LoanScheduleRow */
        LoanScheduleRow: {
            /** Period Month */
            period_month: number;
            /** Payment Yen */
            payment_yen: number;
            /** Interest Yen */
            interest_yen: number;
            /** Principal Yen */
            principal_yen: number;
            /** Balance Yen */
            balance_yen: number;
        };
        /**
         * MarketBenchmark
         * @description 相場ベンチマーク (任意)。
         *
         *     値が None のフィールドはスキップ。
         */
        MarketBenchmark: {
            /** Rent Per Sqm Monthly P25 */
            rent_per_sqm_monthly_p25?: number | null;
            /** Rent Per Sqm Monthly P50 */
            rent_per_sqm_monthly_p50?: number | null;
            /** Rent Per Sqm Monthly P75 */
            rent_per_sqm_monthly_p75?: number | null;
            /** Area Vacancy Rate P50 */
            area_vacancy_rate_p50?: number | null;
            /** Market Cap Rate P50 */
            market_cap_rate_p50?: number | null;
        };
        /** MaxOfferRequest */
        MaxOfferRequest: {
            assumptions: components["schemas"]["Assumptions"];
            targets?: components["schemas"]["InvestorTargets"] | null;
        };
        /** MaxOfferResult */
        MaxOfferResult: {
            /** Current Price Yen */
            current_price_yen: number;
            /** Max Price Yen */
            max_price_yen: number;
            /** Safe Price Yen */
            safe_price_yen: number;
            /** Required Discount Yen */
            required_discount_yen: number;
            /** Binding Constraints */
            binding_constraints?: string[];
            /** Iterations */
            iterations: number;
            /** Converged */
            converged: boolean;
        };
        /** OpexAssumptions */
        OpexAssumptions: {
            /**
             * Management Fee Rate
             * @default 0.05
             */
            management_fee_rate: number;
            /**
             * Repair Reserve Monthly Yen
             * @default 0
             */
            repair_reserve_monthly_yen: number;
            /**
             * Fixed Property Tax Yen
             * @default 0
             */
            fixed_property_tax_yen: number;
            /**
             * Insurance Yen
             * @default 0
             */
            insurance_yen: number;
            /**
             * Building Mgmt Yen
             * @default 0
             */
            building_mgmt_yen: number;
            /**
             * Other Opex Yen
             * @default 0
             */
            other_opex_yen: number;
            /**
             * Opex Growth Rate
             * @default 0.005
             */
            opex_growth_rate: number;
        };
        /** PatchDealRequest */
        PatchDealRequest: {
            /** Title */
            title?: string | null;
            /** Status */
            status?: string | null;
            /** Property Type */
            property_type?: string | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** PropertyAssumptions */
        PropertyAssumptions: {
            /**
             * Property Type
             * @enum {string}
             */
            property_type: "kuubun" | "ittou_apt" | "ittou_mansion" | "kodate" | "land";
            /** Purchase Price Yen */
            purchase_price_yen: number;
            /** Land Value Yen */
            land_value_yen: number;
            /** Building Value Yen */
            building_value_yen: number;
            /**
             * Structure
             * @enum {string}
             */
            structure: "wood" | "steel" | "rc" | "src";
            /** Building Completion Ym */
            building_completion_ym: string;
            /** Acquisition Year */
            acquisition_year: number;
            /** Building Area Sqm */
            building_area_sqm: number;
            /** Land Area Sqm */
            land_area_sqm?: number | null;
            /** Num Units */
            num_units?: number | null;
            /** Location Pref */
            location_pref: string;
            /** Location City */
            location_city?: string | null;
        };
        /**
         * PropertyBrochureExtraction
         * @description 販売図面から取れる主要 26 項目 (v1)。
         *
         *     LLM の型ゆれを吸収するため Before validator で coerce。
         */
        PropertyBrochureExtraction: {
            /** Property Name */
            property_name?: string | null;
            /** Address */
            address?: string | null;
            /** Asking Price Yen */
            asking_price_yen?: number | null;
            /** Nearest Station */
            nearest_station?: string | null;
            /** Station Walk Min */
            station_walk_min?: number | null;
            /** Land Area Sqm */
            land_area_sqm?: number | null;
            /** Building Area Sqm */
            building_area_sqm?: number | null;
            /** Exclusive Area Sqm */
            exclusive_area_sqm?: number | null;
            /** Structure */
            structure?: ("wood" | "rc" | "src" | "steel") | null;
            /** Floors Above */
            floors_above?: number | null;
            /** Num Units */
            num_units?: number | null;
            /** Floor Plan */
            floor_plan?: string | null;
            /** Build Year Month */
            build_year_month?: string | null;
            /** Zoning */
            zoning?: string | null;
            /** Bcr Pct */
            bcr_pct?: number | null;
            /** Far Pct */
            far_pct?: number | null;
            /** Road Frontage */
            road_frontage?: string | null;
            /** Gross Yield Pct */
            gross_yield_pct?: number | null;
            /** Estimated Full Rent Monthly Yen */
            estimated_full_rent_monthly_yen?: number | null;
            /** Management Fee Monthly Yen */
            management_fee_monthly_yen?: number | null;
            /** Repair Reserve Monthly Yen */
            repair_reserve_monthly_yen?: number | null;
            /** Notes */
            notes?: string | null;
            /** Field Confidences */
            field_confidences?: {
                [key: string]: number;
            };
            /** Inferred Fields */
            inferred_fields?: unknown[];
        };
        /** SaveAnalysisRequest */
        SaveAnalysisRequest: {
            /**
             * Source Type
             * @default manual
             */
            source_type: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Extracted */
            extracted?: {
                [key: string]: unknown;
            } | null;
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            };
            /** Analysis Result */
            analysis_result: {
                [key: string]: unknown;
            };
            /** Assumption Score */
            assumption_score: {
                [key: string]: unknown;
            };
            /** Pii Redactions */
            pii_redactions?: {
                [key: string]: number;
            };
            /** Warnings */
            warnings?: string[];
        };
        /** SaveAnalysisResponse */
        SaveAnalysisResponse: {
            /** Id */
            id: string;
        };
        /** ScenarioResult */
        ScenarioResult: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "base" | "rent_down_5" | "rent_down_10" | "vacancy_up_5pt" | "vacancy_up_10pt" | "rate_up_50bp" | "rate_up_100bp" | "opex_15x" | "opex_20x" | "exit_cap_up_25bp" | "exit_cap_up_50bp" | "combined_stress";
            /** Atcf Year1 Yen */
            atcf_year1_yen: number;
            /** Irr */
            irr: number | null;
            /** Dscr Min */
            dscr_min: number;
            /** Net Proceeds Yen */
            net_proceeds_yen: number;
            /**
             * Judgment
             * @enum {string}
             */
            judgment: "good" | "warn" | "bad";
        };
        /** SensitivityRequest */
        SensitivityRequest: {
            assumptions: components["schemas"]["Assumptions"];
        };
        /** SensitivityResult */
        SensitivityResult: {
            base: components["schemas"]["ScenarioResult"];
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioResult"][];
        };
        /** SummarizeRequest */
        SummarizeRequest: {
            /** Analysis Result */
            analysis_result: {
                [key: string]: unknown;
            };
            /** Assumption Score */
            assumption_score: {
                [key: string]: unknown;
            };
            /** Needs Confirmation */
            needs_confirmation?: string[];
        };
        /** SummarizeResponse */
        SummarizeResponse: {
            /** Summary Lines */
            summary_lines: string[];
            /** Questions */
            questions: components["schemas"]["InquiryQuestionOut"][];
            /** Ng Filtered */
            ng_filtered: boolean;
            /** Model */
            model: string;
        };
        /** TaxAssumptions */
        TaxAssumptions: {
            /**
             * Income Tax Rate
             * @default 0.2
             */
            income_tax_rate: number;
            /**
             * Resident Tax Rate
             * @default 0.1
             */
            resident_tax_rate: number;
            /**
             * Business Tax Rate
             * @default 0
             */
            business_tax_rate: number;
            /**
             * Capital Gain Short Rate
             * @default 0.39
             */
            capital_gain_short_rate: number;
            /**
             * Capital Gain Long Rate
             * @default 0.2
             */
            capital_gain_long_rate: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** YearlyCashflow */
        YearlyCashflow: {
            /** Year */
            year: number;
            /** Gpi Yen */
            gpi_yen: number;
            /** Vacancy Loss Yen */
            vacancy_loss_yen: number;
            /** Bad Debt Yen */
            bad_debt_yen: number;
            /** Egi Yen */
            egi_yen: number;
            /** Opex Yen */
            opex_yen: number;
            /** Noi Yen */
            noi_yen: number;
            /** Debt Service Yen */
            debt_service_yen: number;
            /** Btcf Yen */
            btcf_yen: number;
            /** Depreciation Yen */
            depreciation_yen: number;
            /** Interest Expense Yen */
            interest_expense_yen: number;
            /** Principal Payment Yen */
            principal_payment_yen: number;
            /** Taxable Income Yen */
            taxable_income_yen: number;
            /** Tax Yen */
            tax_yen: number;
            /** Atcf Yen */
            atcf_yen: number;
            /** Loan Balance End Yen */
            loan_balance_end_yen: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_deals_deals_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deal_deals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deal_deals__deal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deal_deals__deal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_deal_deals__deal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchDealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analysis_runs_deals__deal_id__analysis_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_run_deals__deal_id__analysis_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysisRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_run_analysis_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bid_ranges_analysis_runs__run_id__bid_ranges_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidRangesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_bid_ranges_analysis_runs__run_id__bid_ranges_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BidRangesGenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidRangesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assumption_risks_analysis_runs__run_id__assumption_risks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssumptionRisksListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_assumption_risks_analysis_runs__run_id__assumption_risks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AssumptionRisksGenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssumptionRisksListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_nishi_shinjuku_sample_nishi_shinjuku_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
        };
    };
    post_max_offer_max_offer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaxOfferRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaxOfferResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_sensitivity_sensitivity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensitivityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cross_asset_cross_asset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrossAssetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossAssetResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_extract_url_extract_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_extract_document_extract_document_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_extract_document_extract_document_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analyses_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_save_analysis_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_by_id_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_expired_documents_admin_purge_expired_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    post_summarize_summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummarizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_critique_critique_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CritiqueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CritiqueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
