"""Figure registry for the johnhull portal.

Mirrors ``analytics/report``: every :class:`FigureSpec` returns a Plotly
``go.Figure`` from shared hullkit builders (including the internal binary
lesson) or versioned reference artifacts. Shared sources reduce duplication;
semantic tests and rendered checks verify the displayed values and behavior.

Adding a figure = append one ``FigureSpec``. Adding a theme = one ``BookMeta``.
New deep-dive volumes (A1 stochastic calculus, A2 stoch-vol/Fourier, A3 advanced
numerics, A4 XVA) and the vol 18–28 frontier volumes register their figures here.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from hullkit import plotly_viz as pv
from hullkit._alternative_models_lesson import _figures as alternative_models_lesson_figures
from hullkit._asian_lesson import _figures as asian_lesson_figures
from hullkit._basket_lesson import _figures as basket_lesson_figures
from hullkit._binary_lesson import _figures as binary_lesson_figures
from hullkit._exchange_lesson import _figures as exchange_lesson_figures
from hullkit._lookback_lesson import _figures as lookback_lesson_figures
from hullkit._shout_lesson import _figures as shout_lesson_figures
from hullkit._static_replication_lesson import _figures as static_replication_lesson_figures
from hullkit._variance_swap_lesson import _figures as variance_swap_lesson_figures

from . import frontier_figures as ff


@dataclass(frozen=True)
class BookMeta:
    key: str
    title: str
    subtitle: str
    accent: str
    book_index: str  # relative path from site/ to the Jupyter Book index


BOOKS: dict[str, BookMeta] = {
    "options_core": BookMeta(
        key="options_core",
        title="オプションの設計図",
        subtitle="ペイオフ・グリークス・ヘッジ",
        accent="#2563eb",
        book_index="../../book/_build/html/index.html",
    ),
    "numerics": BookMeta(
        key="numerics",
        title="数値手法の収束",
        subtitle="格子・モンテカルロ・有限差分",
        accent="#7c3aed",
        book_index="../../book/_build/html/index.html",
    ),
    "risk_credit": BookMeta(
        key="risk_credit",
        title="リスクと信用",
        subtitle="VaR・ES・デフォルト",
        accent="#16a34a",
        book_index="../../book/_build/html/index.html",
    ),
    "stochastic": BookMeta(
        key="stochastic",
        title="確率解析",
        subtitle="伊藤・Girsanov・Feynman-Kac",
        accent="#0891b2",
        book_index="../../book/_build/html/index.html",
    ),
    "volatility": BookMeta(
        key="volatility",
        title="確率ボラティリティ",
        subtitle="Heston・Fourier・SABR",
        accent="#db2777",
        book_index="../../book/_build/html/index.html",
    ),
    "rates_swaps": BookMeta(
        key="rates_swaps",
        title="金利とスワップ",
        subtitle="カーブ・デュレーション・スワップ",
        accent="#ca8a04",
        book_index="../../book/_build/html/index.html",
    ),
    "exotics": BookMeta(
        key="exotics",
        title="エキゾチック",
        subtitle="バリア・アジアン",
        accent="#0d9488",
        book_index="../../book/_build/html/index.html",
    ),
    "ml_derivatives": BookMeta(
        key="ml_derivatives",
        title="MLとデリバティブ",
        subtitle="surrogate・surface・forecast・hedge",
        accent="#4f46e5",
        book_index="../../book/_build/html/index.html",
    ),
    "volatility_frontiers": BookMeta(
        key="volatility_frontiers",
        title="ボラ最前線",
        subtitle="joint SPX/VIX・0DTE",
        accent="#e11d48",
        book_index="../../book/_build/html/index.html",
    ),
    "crypto_market": BookMeta(
        key="crypto_market",
        title="Crypto市場構造",
        subtitle="perpetual・liquidation・AMM",
        accent="#f97316",
        book_index="../../book/_build/html/index.html",
    ),
    "climate_energy": BookMeta(
        key="climate_energy",
        title="気候とエネルギー",
        subtitle="carbon・weather・PPA",
        accent="#059669",
        book_index="../../book/_build/html/index.html",
    ),
    "risk_management": BookMeta(
        key="risk_management",
        title="リスク管理デスク",
        subtitle="バックテスト・EVT・配賦・PnL explain",
        accent="#dc2626",
        book_index="../../book/_build/html/index.html",
    ),
}


@dataclass(frozen=True)
class FigureSpec:
    id: str
    book: str
    title: str
    blurb: str  # 何が見えるか
    build: Callable
    is_new: bool = False
    practice: str = ""  # 実務での意味 — なぜ実社会で役立つか


FIGURES: list[FigureSpec] = [
    # options_core -------------------------------------------------------
    FigureSpec(
        "strategy_payoffs",
        "options_core",
        "オプション戦略のペイオフ",
        "ブル/ストラドル/バタフライ…をドロップダウンで切替。脚の足し合わせが戦略の形を作る(Hull Ch.12)。",
        pv.plotly_strategy_payoffs,
        practice="セールスが顧客の相場観を『形』に翻訳する道具。脚の組み合わせで損益図を設計する。",
    ),
    FigureSpec(
        "delta_vs_spot",
        "options_core",
        "デルタは満期で鋭くなる",
        "残存 T を縮めるとコールデルタが滑らかな S 字 → ストライクでの段差へ。ガンマ急増の理由(Hull Ch.19)。",
        pv.plotly_delta_vs_spot,
        practice="満期が近いほどデルタが段差化＝ガンマ急騰。決算跨ぎ短期 ATM のヘッジが最難関な理由。",
        is_new=True,
    ),
    FigureSpec(
        "delta_hedge_cost",
        "options_core",
        "デルタヘッジ費用が BSM 価格へ締まる",
        "リヘッジ回数を増やすとヘッジ費用の分布が BSM 価格(破線)の周りに収束。実ドリフトに依らない(Hull §19.4)。",
        pv.plotly_delta_hedge_cost,
        practice="マーケットメイカーの損益分布そのもの。建値(BSM)へ締まる＝方向観に依らず鞘を取れる。",
        is_new=True,
    ),
    # numerics -----------------------------------------------------------
    FigureSpec(
        "tree_convergence",
        "numerics",
        "二項木 → BSM 収束",
        "ステップ数 N を上げると CRR 価格が鋸歯状に振動しながら閉形式へ収束する(Hull Ch.13)。",
        pv.plotly_tree_convergence,
        practice="閉形式の無い商品を木で値付ける際の必要ステップ数の目安。木と BSM の一致は実装の検算。",
    ),
    # numerics (A3) ------------------------------------------------------
    FigureSpec(
        "mc_variance_reduction",
        "numerics",
        "分散減少と QMC の収束",
        "価格誤差 vs N を手法別に両対数で。制御変量は水準を下げ、Sobol QMC は傾きを N⁻¹ へ近づける。",
        pv.plotly_mc_variance_reduction,
        practice="XVA 等の重い MC を実用化する鍵。同じ精度を桁違いに少ない計算で得る。",
        is_new=True,
    ),
    FigureSpec(
        "qmc_vs_pseudo",
        "numerics",
        "擬似乱数 vs Sobol 列",
        "単位正方形上の点。擬似乱数はむら・隙間、Sobol は一様に空間を埋める(低食い違い)。",
        pv.plotly_qmc_vs_pseudo,
        practice="高次元の値付けを速くする低食い違い列。実務 MC が QMC を使う理由が目で分かる。",
        is_new=True,
    ),
    FigureSpec(
        "american_boundary",
        "numerics",
        "アメリカンプットの早期行使境界",
        "Crank-Nicolson から読む S*(τ)。境界より下で行使。σ を上げると境界は下がる(待つ価値)。",
        pv.plotly_american_boundary,
        practice="『いつ行使・解約すべきか』の境界。コーラブル債・期前償還の実務判断に直結。",
        is_new=True,
    ),
    FigureSpec(
        "alternative_cev",
        "numerics",
        "CEV：株価と局所ボラ",
        "β<1では株価下落とともに局所ボラが上がる。S₀=100で20%に揃えて比較する（Hull §27.1）。",
        lambda: alternative_models_lesson_figures()["alternative_cev"],
        practice="βだけを変えても同じσを使えば比較条件がずれる。開始時点の局所ボラを固定する。",
        is_new=True,
    ),
    FigureSpec(
        "alternative_merton",
        "numerics",
        "Merton：下向きジャンプとスキュー",
        "ジャンプ補償を入れた欧州価格をBSM-IVに戻すと、短期の左側が高くなる（Hull §27.1）。",
        lambda: alternative_models_lesson_figures()["alternative_merton"],
        practice="下落ジャンプの頻度・大きさを変えると短期の尾部価格が大きく動く。",
        is_new=True,
    ),
    FigureSpec(
        "alternative_poisson",
        "numerics",
        "Table 27.1：ジャンプ回数",
        "λ=0.5/年、T=2年での回数別確率と累積確率を原典の表示桁で示す。",
        lambda: alternative_models_lesson_figures()["alternative_poisson"],
        practice="1回以上のジャンプ確率は約63.2%。回数ごとのシナリオ重みを確認する。",
        is_new=True,
    ),
    FigureSpec(
        "alternative_vg",
        "numerics",
        "Figure 27.1：VG と GBM の満期株価",
        "ガンマ時計で変動する満期株価の標本密度を、同じ拡散σのGBM対数正規密度と比較する。",
        lambda: alternative_models_lesson_figures()["alternative_vg"],
        practice="裾はモデルと満期・歪みパラメータに依存する。図は40万標本の有限誤差を含む。",
        is_new=True,
    ),
    # risk_credit --------------------------------------------------------
    FigureSpec(
        "var_es",
        "risk_credit",
        "VaR と ES を信頼水準で動かす",
        "信頼水準を上げると VaR(とその外側の ES)が損失テールへ深く移動。ヒストリカル法(Hull Ch.22)。",
        pv.plotly_var_es,
        practice="銀行の規制資本・リスク限度の根幹。Basel が VaR から ES へ移った理由を体感できる。",
        is_new=True,
    ),
    FigureSpec(
        "credit_survival",
        "risk_credit",
        "生存確率と CDS スプレッド",
        "ハザード率 λ を上げると生存曲線が速く減衰し、5Y CDS パースプレッドが拡大する(Hull Ch.24-25)。",
        pv.plotly_credit_survival,
        practice="CDS スプレッドから読む信用の市場評価。ハザード率と価格の対応。",
        is_new=True,
    ),
    # XVA & counterparty credit (A4) -------------------------------------
    FigureSpec(
        "exposure_profile",
        "risk_credit",
        "エクスポージャ EE / PFE",
        "フォワードの期待エクスポージャ EE(CVA を駆動)と PFE(限度枠)。σ で両者が広がる。",
        pv.plotly_exposure_profile,
        practice="CVA を駆動する EE と限度枠の PFE。カウンターパーティ・リスク管理の基礎量。",
        is_new=True,
    ),
    FigureSpec(
        "cva_sensitivity",
        "risk_credit",
        "CVA の時間分解とハザード感応度",
        "CVA 被積分項 (1−R)·DF·EE·ΔPD を時間軸に展開。λ を上げると総額(タイトル、bp 表示)が増え、重みが手前に移る。",
        pv.plotly_cva_sensitivity,
        practice="CVA は『エクスポージャが大きい時期』と『デフォルトしやすい時期』の重なり。CVA デスクのプライシングの直感。",
        is_new=True,
    ),
    FigureSpec(
        "portfolio_loss",
        "risk_credit",
        "ポートフォリオ損失 vs 相関",
        "1ファクター・ガウシアンコピュラ。平均は pd 不変、相関 ρ↑ で損失分布のテールが肥大(2008年の本質)。",
        pv.plotly_portfolio_loss_correlation,
        practice="相関こそシステミックリスク。平均は不変でテールだけ肥大＝2008年の本質。",
        is_new=True,
    ),
    FigureSpec(
        "copula_scatter",
        "risk_credit",
        "コピュラ散布とテール依存",
        "ガウシアンコピュラ標本。ρ↑ で点が対角に集まり、名柄が同時にデフォルトしやすくなる。",
        pv.plotly_copula_scatter,
        practice="相関↑ で名柄が同時にデフォルトしやすくなる様子。CDO が崩れた仕組み。",
        is_new=True,
    ),
    # stochastic (A1) ----------------------------------------------------
    FigureSpec(
        "quadratic_variation",
        "stochastic",
        "二次変分 [W]_t → t",
        "ブラウン運動の累積 Σ(ΔW)² が、分割を細かくするほど直線 y=t に張り付く(Shreve II §3.4)。",
        pv.plotly_quadratic_variation,
        practice="二次変分 → t が伊藤の ½σ² 項の源。あらゆる価格 PDE の出発点。",
        is_new=True,
    ),
    FigureSpec(
        "ito_correction",
        "stochastic",
        "伊藤 vs Stratonovich",
        "∫W dW の左点和(伊藤)と中点和(Stratonovich)の差 ½[W]_T → ½T が伊藤の補正項(Shreve II §4.3)。",
        pv.plotly_ito_correction,
        practice="伊藤 vs Stratonovich の差＝½T。確率版の連鎖律がなぜ要るか。",
        is_new=True,
    ),
    FigureSpec(
        "girsanov",
        "stochastic",
        "Girsanov: 実世界 μ を変えても Q は不変",
        "実世界ドリフト μ を動かしても、測度変換後のリスク中立分布と Q コール価格は動かない(Shreve II §5.2-5.4)。",
        pv.plotly_girsanov,
        practice="実世界 μ を動かしても Q 価格は不変。リスク中立評価が成り立つ理由の可視化。",
        is_new=True,
    ),
    # volatility (A2) ----------------------------------------------------
    FigureSpec(
        "heston_smile",
        "volatility",
        "Heston スマイルと ρ",
        "Heston 価格(COS)を逆算した IV スマイル。ρ<0 で下方スキュー、ξ で曲率(Gatheral Ch.3)。",
        pv.plotly_heston_smile,
        practice="ρ で傾き・ξ で曲率。市場スマイルへのカリブレーションのパラメータ感覚。",
        is_new=True,
    ),
    FigureSpec(
        "cos_convergence",
        "volatility",
        "COS 法の密度収束",
        "特性関数から復元した密度が項数 N を増やすと基準へ収束。少数項で十分(Fang-Oosterlee)。",
        pv.plotly_cos_density_convergence,
        practice="特性関数 → 密度を少数項で復元。Heston 高速値付けの心臓部。",
        is_new=True,
    ),
    FigureSpec(
        "sabr_smile",
        "volatility",
        "SABR スマイルと vol-of-vol",
        "Hagan 公式の IV スマイル。ν で曲率、ρ<0 で傾き、ATM を揃えた β 比較でバックボーンのスキューも見える。",
        pv.plotly_sabr_smile,
        practice="金利スマイルの市場標準。ブローカー画面が SABR パラメータで気配を出す理由。",
        is_new=True,
    ),
    FigureSpec(
        "iv_surface",
        "volatility",
        "Heston IV サーフェス IV(K, T)",
        "COS 価格を逆算した IV をストライク×満期の曲面に。ρ<0 が全満期を株式スキューへ傾け、満期とともにスマイルが平坦化。",
        pv.plotly_iv_surface,
        practice="デスクが毎朝見るボラサーフェスそのもの。スマイルと期間構造を1枚で掴むカリブレーションの出発点。",
        is_new=True,
    ),
    FigureSpec(
        "smile_model_risk",
        "volatility",
        "同じスマイル、違う Greeks — β のモデルリスク",
        "同一の市場スマイルに β=0/0.5/1 の SABR を再校正。フィットは市場点に重なり区別不能なのに、Δ・Γ・ベガが揃って乖離する。",
        pv.plotly_smile_model_risk,
        practice="市場価格が決めてくれない選択(β)がヘッジ全体を決める — Hagan (2002) の中心命題。モデル検証・リザーブの根拠。",
        is_new=True,
    ),
    FigureSpec(
        "sabr_greeks_by_param",
        "volatility",
        "SABR パラメータを動かすと Greeks はどう変わるか",
        "α/β/ρ/ν をドロップダウンで選び、5値スイープの Δ・Γ・V・Θ 曲線。全スイープが基準線(accent)を通り、各ノブが Greeks をどう引き剥がすかが見える。",
        pv.plotly_sabr_greeks_by_param,
        practice="どのパラメータを動かすと、どの Greek が・どのストライクで動くか。β 以外(α・ρ・ν)も含めたヘッジの依存構造を一望する。",
        is_new=True,
    ),
    FigureSpec(
        "sabr_rho_nu_smile_greeks",
        "volatility",
        "ρ と ν はスマイルをどう変え、Greeks がどう追随するか",
        "行=ρ/ν、列=スマイル IV・Δ・Γ の 5値スイープ。ρ はスマイルを傾けΔを歪め、ν は翼を持ち上げΓを膨らませる — スマイル変化→ヘッジ変化の連鎖。",
        pv.plotly_sabr_rho_nu_smile_greeks,
        practice="β の影に隠れがちな ρ・ν の役割。スマイルの傾き・曲率を動かすと、ヘッジのどこがどう崩れるかを左右に並べて読む。",
        is_new=True,
    ),
    FigureSpec(
        "sabr_param_greeks",
        "volatility",
        "どのパラメータがどの Greek に効くか",
        "標準化バンプ(α+1volpt/β+0.1 ATM揃え/ρ+0.1/ν+0.1)× Δ・Γ・V・Θ の変化率ヒートマップ。行内の赤青混在＝トレードオフ。K スライダー。",
        pv.plotly_sabr_param_greeks,
        practice="キャリブレーションの自由度はヘッジの自由度。あるGreekを合わせると別のGreekがずれる構造を、バンプ前に地図で知る。",
        is_new=True,
    ),
    # extra coverage -----------------------------------------------------
    FigureSpec(
        "gamma_surface",
        "options_core",
        "ガンマ曲面 Γ(S, T)",
        "ガンマはストライク近傍・満期直前で尖る。ATM オプションが満期間際に最もヘッジしにくい理由。",
        pv.plotly_gamma_surface,
        practice="ATM・満期直前で最もヘッジしにくい領域が一目で分かる。在庫の危険ゾーンの地図。",
        is_new=True,
    ),
    FigureSpec(
        "greeks_map",
        "options_core",
        "グリークスの地図(ベガ・セータ・バンナ・ボンマ)",
        "S×残存 T のヒートマップをドロップダウンで切替。ベガ/ボンマは長期に、セータは満期直前 ATM に、バンナは翼に住む。",
        pv.plotly_greeks_map,
        practice="スマイルリスク(バンナ・ボンマ)がブックのどこに溜まるかの地図。ボラデスクのリスクレポートの縮図。",
        is_new=True,
    ),
    FigureSpec(
        "bsm_greeks_sensitivity",
        "options_core",
        "Greeks はボラ入力にどう依存するか",
        "Δ・Γ・Θ・V の4面 vs S。ヘッジ入力 σ を動かすと、同じ点 S=K(点線)での Greeks がすべて動く — 入力リスク。",
        pv.plotly_bsm_greeks_sensitivity,
        practice="古い・誤ったボラマークを入れると全ヘッジ比率が狂う。EODマークとリアルタイムヘッジの乖離という日常的リスク。",
        is_new=True,
    ),
    FigureSpec(
        "stop_loss_vs_delta",
        "options_core",
        "ストップロス vs デルタヘッジ",
        "素朴なストップロスは偏り・分散が大きい。デルタヘッジは BSM 価格に締まる(Hull §19.2)。",
        pv.plotly_stop_loss_vs_delta_hedge,
        practice="『直感的に正しそうな』ストップロスが破綻する反面教師。複製の規律がなぜ要るか。",
        is_new=True,
    ),
    FigureSpec(
        "binomial_lattice",
        "numerics",
        "二項木格子と後ろ向き帰納",
        "CRR 格子そのもの。ノードの色がオプション価値、アメリカンの早期行使域が見える(Hull Ch.13)。",
        pv.plotly_binomial_lattice,
        practice="後退帰納とアメリカンの早期行使域を格子上で。エキゾチック評価器の基礎。",
        is_new=True,
    ),
    FigureSpec(
        "garch_volatility",
        "volatility",
        "ボラのクラスタリング(EWMA/GARCH)",
        "EWMA と GARCH(1,1) の年率ボラ。荒れた時期が固まり、GARCH は長期水準へ平均回帰(Hull Ch.23)。",
        pv.plotly_garch_volatility,
        practice="ボラのクラスタリングと平均回帰。危機時の VaR 過小評価を防ぐ動学。",
        is_new=True,
    ),
    FigureSpec(
        "garch_term_structure",
        "volatility",
        "GARCH 予測の期間構造",
        "出発が高ボラでも低ボラでも、予測は長期ボラへ平均回帰。ボラの期間構造の素。",
        pv.plotly_garch_term_structure,
        practice="高/低ボラから長期水準への回帰。ボラの期間構造＝満期別オプション値付けの素。",
        is_new=True,
    ),
    FigureSpec(
        "merton_structural",
        "risk_credit",
        "Merton 構造模型",
        "株式 = 資産のコール。負債・資産ボラを上げるとデフォルト確率が上がる(Hull §24.6)。",
        pv.plotly_merton_structural,
        practice="株価から信用を読む(KMV の distance-to-default)。資産ボラ・レバレッジと PD の関係。",
        is_new=True,
    ),
    FigureSpec(
        "portfolio_diversification",
        "risk_credit",
        "分散投資と相関の床",
        "独立なら 1/√N で減るが、相関 ρ があると √ρ·σ の床が残る(分散しきれないリスク)。",
        pv.plotly_portfolio_diversification,
        practice="分散しきれないリスクの『床』。相関がある限り 1/√N では消えない。",
        is_new=True,
    ),
    FigureSpec(
        "yield_curve",
        "rates_swaps",
        "イールドカーブとフォワード",
        "順イールドではフォワードがゼロ金利の上、逆イールドでは下に来る(Hull Ch.4)。",
        pv.plotly_yield_curve,
        practice="順/逆イールドとフォワードの関係。将来金利の市場予想の読み取り。",
        is_new=True,
    ),
    FigureSpec(
        "bond_convexity",
        "rates_swaps",
        "債券の価格-利回りとコンベクシティ",
        "価格-利回り曲線は凸。デュレーション(接線)が捉え損なう曲率がコンベクシティ(Hull Ch.4)。",
        pv.plotly_bond_convexity,
        practice="デュレーション(接線)が捉え損なう曲率。債券リスク管理の基本量。",
        is_new=True,
    ),
    FigureSpec(
        "swap_value",
        "rates_swaps",
        "金利スワップの価値と par レート",
        "受取固定スワップ価値は固定金利に対して線形で、par スワップレートでちょうど 0(Hull Ch.7)。",
        pv.plotly_swap_value,
        practice="受取固定スワップ価値は固定金利に線形、par で 0。世界最大級のデリバ市場の評価。",
        is_new=True,
    ),
    FigureSpec(
        "barrier_knockout",
        "exotics",
        "バリア・オプション8種類",
        "call/put・up/down・in/out を切替え、連続観測の in + out = vanilla と H=S₀ の到達境界を比較する(Hull GE §26.9 pp.620–622)。",
        pv.plotly_barrier_knockout,
        practice="同じ契約・観測規則の組を比較する。離散観測の BGK 近似、負のベガ、Parisian の滞在条件は第10冊で確認。",
        is_new=True,
    ),
    FigureSpec(
        "binary_payoffs",
        "exotics",
        "バイナリー4契約の満期給付",
        "S₀=K=100、r=5%、q=2%、σ=20%、T=1年、Q=100。cash/asset × call/put の跳びと K での決済を比較する。",
        lambda: binary_lesson_figures()["binary_payoffs"],
        practice="約定時に K の等号規約、参照価格、時刻、丸めを確定し、片側極限と実際の決済を区別する。",
        is_new=True,
    ),
    FigureSpec(
        "binary_replication",
        "exotics",
        "バイナリーによる call/put 複製",
        "S₀=K=100、r=5%、q=2%、σ=20%、T=1年。cash leg の Q=K と asset leg からバニラ給付を再構成する。",
        lambda: binary_lesson_figures()["binary_replication"],
        practice="ドロップダウンで call/put を切り替え、各 leg の符号と満期給付の分解を照合する。",
        is_new=True,
    ),
    FigureSpec(
        "binary_spreads",
        "exotics",
        "スプレッド極限と密度",
        "S₀=K=100、r=5%、q=2%、σ=20%、T=1年。幅 h=1,5,15 の centered spread と butterfly の満期給付を比較する。",
        lambda: binary_lesson_figures()["binary_spreads"],
        practice="centered spread は K で 1/2。デジタルへの収束は K 以外で読み、正規化 butterfly の価格極限を割引終端密度として扱う。",
        is_new=True,
    ),
    FigureSpec(
        "binary_delta",
        "exotics",
        "cash binary の有限時間デルタ",
        "S₀≈K=100、r=5%、q=2%、σ=20%、Q=100。T=1年、30日、1日の有限デルタが満期接近で集中する様子を示す。",
        lambda: binary_lesson_figures()["binary_delta"],
        practice="各 T>0 ではデルタは有限。短期 ATM の急峻化を満期での不連続な極限と混同せず管理する。",
        is_new=True,
    ),
    FigureSpec(
        "lookback_payoffs",
        "exotics",
        "ルックバック4契約と過去の極値",
        "K=100、今日と満期を含む折れ線経路。新規／過去の極値ありを切り替え、4契約の満期給付（通貨）を比較する。",
        lambda: lookback_lesson_figures()["lookback_payoffs"],
        practice="棒は現在価格ではない。m₀=80、M₀=130 の履歴を与えると将来経路が同じでも給付が変わる。",
        is_new=True,
    ),
    FigureSpec(
        "lookback_history",
        "exotics",
        "過去の最小値・最大値と現在価格",
        "S₀=100、r=5%、q=2%、σ=20%、T=1年の連続観測 GBM。横軸は過去の極値、縦軸は現在価格（通貨）。",
        lambda: lookback_lesson_figures()["lookback_history"],
        practice="K を変え、fixed の平坦部分と floating の K 非依存性を確認する。S₀,T,σ>0、有効な履歴が前提。abs(r-q)<1e-8 は既存 API 未対応。",
        is_new=True,
    ),
    FigureSpec(
        "lookback_replication",
        "exotics",
        "固定型ルックバックの価格複製",
        "S₀=100、m₀=85、M₀=120、r=5%、q=2%、σ=20%、T=1年。M₀*=max(M₀,K)、m₀*=min(m₀,K) を使う。",
        lambda: lookback_lesson_figures()["lookback_replication"],
        practice="全脚は現在価値（通貨）。call は p*+S₀e⁻ᑫᵀ−Ke⁻ʳᵀ、put は c*−S₀e⁻ᑫᵀ+Ke⁻ʳᵀ。給付恒等式と割引後の価格を区別する。",
        is_new=True,
    ),
    FigureSpec(
        "lookback_monitoring",
        "exotics",
        "fixing 頻度と満期給付",
        "K=100、m₀=M₀=100。今日・満期を含む1/2/4/8区間で同じ決定論的折れ線を観測する。",
        lambda: lookback_lesson_figures()["lookback_monitoring"],
        practice="8区間はこの折れ線の極値を完全に捕捉する。連続 GBM の極値・価格収束の検証ではない。解析式は連続観測を仮定する。",
        is_new=True,
    ),
    FigureSpec(
        "shout_payoff",
        "exotics",
        "シャウトの満期給付",
        "K=50、Sτ=60 または50。一度だけ利益を確保し、その後の上昇にも参加する。",
        lambda: shout_lesson_figures()["shout_payoff"],
        practice="満期給付と現在価値を区別する。文字通りの給付と内在価値の床は Sτ≥K で一致する。",
        is_new=True,
    ),
    FigureSpec(
        "shout_decision",
        "exotics",
        "シャウト判断の小さな二項木",
        "S₀=K=100、r=5%、q=2%、σ=20%、T=1年、N=3。継続と即時シャウトを比較する。",
        lambda: shout_lesson_figures()["shout_decision"],
        practice="符号付き現金脚と ATM call 脚を個別に確認する。N=3 は手順の図で、精密価格ではない。",
        is_new=True,
    ),
    FigureSpec(
        "shout_boundary",
        "exotics",
        "シャウト境界と格子収束",
        "実際の CRR 層の節点区間と独立 B 境界を比較する。残差は各市場の ATM call。",
        lambda: shout_lesson_figures()["shout_boundary"],
        practice="CRR の上下節点は連続境界を囲む保証がない。42行の最大残差は経験的検査で、証明された誤差上界ではない。",
        is_new=True,
    ),
    FigureSpec(
        "shout_comparison",
        "exotics",
        "同条件の欧州・シャウト・ルックバック",
        "7つの合成市場、K=100、S₀=80/100/125。call の現在価格を比較する。",
        lambda: shout_lesson_figures()["shout_comparison"],
        practice="連続観測・同じ一定係数 GBM・新規極値、S/K/T/σ>0 が条件。r=q の lookback は既存 API 未対応のため欠測であり、0ではない。現金配当・時変ボラティリティ・契約固有の離散シャウト日・T=0/σ=0・全領域の安定性は対象外。put は原典外の拡張で、この図は call。",
        is_new=True,
    ),
    FigureSpec(
        "asian_payoff",
        "exotics",
        "アジアンの満期給付",
        "定義した折れ線経路（K=100、観測8日）。平均価格型と平均行使型で何と何を比べるかが違う。",
        lambda: asian_lesson_figures()["asian_payoff"],
        practice="満期給付であって現在価値ではない。今日は観測日に入らない。折れ線は定義した例で GBM 標本ではない。",
        is_new=True,
    ),
    FigureSpec(
        "asian_distribution",
        "exotics",
        "平均の分布とモーメント整合",
        "観測52日、20万パス。算術平均の分布に、1次・2次モーメントを合わせた対数正規を重ねる。",
        lambda: asian_lesson_figures()["asian_distribution"],
        practice="平均と分散は一致するが形は一致しない。実測の歪度は当てはめた対数正規より大きく、その差が価格の誤差になる。固定シードの標本で、密度の厳密解ではない。",
        is_new=True,
    ),
    FigureSpec(
        "asian_observations",
        "exotics",
        "観測数と平均価格オプション",
        "観測 12/52/250 と連続平均。原著の 6.00 / 5.70 / 5.63 と同じ規約（i·T/m、今日を除き満期を含む）。",
        lambda: asian_lesson_figures()["asian_observations"],
        practice="整合値と参照価格の差は近似誤差で、標準誤差バーとは別物。幾何平均はコール価格の下界。",
        is_new=True,
    ),
    FigureSpec(
        "asian_error",
        "exotics",
        "モーメント整合の誤差",
        "観測52日、6市場、S/K=0.8/1.0/1.25。制御変量モンテカルロの参照価格に対する相対誤差。",
        lambda: asian_lesson_figures()["asian_error"],
        practice="誤差は片側でない。σ√T が大きいほど悪化するが、キャリーがマネーネスを動かすため σ√T だけでは順序が決まらない。参照価格は標準誤差を持ち、厳密なのは2観測日の行だけ。",
        is_new=True,
    ),
    FigureSpec(
        "exchange_payoff",
        "exotics",
        "交換オプションの満期給付",
        "U_T=100 を渡して V_T を受け取る。better-of / worse-of は同じ給付の足し引きで書ける。",
        lambda: exchange_lesson_figures()["exchange_payoff"],
        practice="満期給付であって現在価値ではない。行使価格が固定額でなく別の資産の価値になる点が普通のオプションとの違い。",
        is_new=True,
    ),
    FigureSpec(
        "exchange_correlation",
        "exotics",
        "相関と交換オプション",
        "ρ を −0.95 から 0.95 まで動かす。価格を決めるのは σ̂=√(σ_U²+σ_V²−2ρσ_Uσ_V) だけである。",
        lambda: exchange_lesson_figures()["exchange_correlation"],
        practice="ρ が高いほど2資産が連動し、比 V/U のばらつきが減って交換の価値は下がる。σ̂→0 では割引フォワードの差に張り付く。",
        is_new=True,
    ),
    FigureSpec(
        "exchange_rate",
        "exotics",
        "リスクフリー金利に依存しない",
        "r を −5% から 12% まで動かした独立参照価格と、V/U への読み替え（行使1.0・金利 q_U・配当 q_V）。",
        lambda: exchange_lesson_figures()["exchange_rate"],
        practice="成長率の上昇と割引率の上昇が相殺するため式26.5に r は現れない。行使価格を今日の U_0 に固定した誤読では r とともに動く。",
        is_new=True,
    ),
    FigureSpec(
        "exchange_american",
        "exotics",
        "米国型と早期行使",
        "Rubinstein の読み替えによる V/U 上の二項木（1024ステップ）。q_V=0 と q_V>0 を比べる。",
        lambda: exchange_lesson_figures()["exchange_american"],
        practice="受け取る資産に配当がなければ早期行使に価値はない。木は有限格子なので、同じ格子で行使判定を外した価格と比べて離散化と早期行使を分離している。",
        is_new=True,
    ),
    FigureSpec(
        "basket_payoff",
        "exotics",
        "バスケットの満期給付",
        "B_T=0.6 S₁(T)+0.5 S₂(T)。コール max(B_T−K,0) とプット max(K−B_T,0) を切り替える。",
        lambda: basket_lesson_figures()["basket_payoff"],
        practice="非負の保有量は単位なし、資産価格・行使価格・給付は通貨単位。ゼロ給付はゼロ保有量を意味しない。CBOT の受渡選択権はレインボーの文脈であり、印刷されたバスケット価格例ではない。",
        is_new=True,
    ),
    FigureSpec(
        "basket_correlation",
        "exotics",
        "相関・厳密なモーメントと近似分布",
        "Fᵢ=wᵢSᵢexp((r−qᵢ)T)、M₁=ΣFᵢ、M₂=ΣᵢΣⱼFᵢFⱼexp(ρᵢⱼσᵢσⱼT)。相関だけを変えた3市場。",
        lambda: basket_lesson_figures()["basket_correlation"],
        practice="M₁・M₂ は相関 GBM 下で厳密。σ̂²=log(M₂/M₁²)/T を使う Black 価格は近似で、和の分布は一般に対数正規ではない。左軸は通貨の二乗、右軸は年率ボラ（%）。",
        is_new=True,
    ),
    FigureSpec(
        "basket_comparison",
        "exotics",
        "近似価格と独立な価格参照",
        "Black 近似 C=e⁻ʳᵀ[M₁N(d₁)−KN(d₂)] と条件付き積分、独立 MC（±4SE）を同じ行使価格で比較する。",
        lambda: basket_lesson_figures()["basket_comparison"],
        practice="d₁=log(M₁/K)/(σ̂√T)+σ̂√T/2、d₂=d₁−σ̂√T。2資産は条件付き積分、3資産は MC を参照する。条件付き積分・解析参照は自身の数値誤差で符号を判定でき、MC の誤差棒内でも符号が確定する場合がある。",
        is_new=True,
    ),
    FigureSpec(
        "basket_error",
        "exotics",
        "観測された誤差と適用範囲",
        "K=100 の絶対相対差と4SEを比較する。斜線は MC だけを参照し |gap|≤4SE となる符号未確定の点。",
        lambda: basket_lesson_figures()["basket_error"],
        practice="保存72行のうち参照価格0.5以上の63行で最大絶対相対誤差66.8378%。普遍的な誤差上限ではない。定数パラメータ・非負保有量・正半定値相関行列の範囲で使い、短期や低ボラでも精度を自動保証しない。",
        is_new=True,
    ),
    FigureSpec(
        "varswap_payoff",
        "exotics",
        "ボラ・スワップとバリアンス・スワップの給付",
        "L_vol(σ−σ_K) と L_var(σ²−σ_K²)、L_var=L_vol/(2σ_K)。Example 26.5 の $100m・23% を満期で描く。",
        lambda: variance_swap_lesson_figures()["varswap_payoff"],
        practice="σ は平均0の日次対数リターンから 252/(n−2) で年率化する（n−1 の契約もある）。換算 L_var=L_vol/(2σ_K) は σ_K での傾きをそろえるだけで、離れるほどバリアンス側が凸性の分だけ大きい。",
        is_new=True,
    ),
    FigureSpec(
        "varswap_strip",
        "exotics",
        "OTM オプションの束で分散を複製する",
        "式26.8：Σ ΔKᵢ/Kᵢ² e^{rT} Q(Kᵢ)。Q は S* の下でプット、上でコール、S* で平均。Example 26.4 で E(V)=0.0621。",
        lambda: variance_swap_lesson_figures()["varswap_strip"],
        practice="Q はインプライド・ボラからこのリポジトリの BSM で再計算し、印刷値と小数2桁で一致。1/K² の重みで低い行使価格が効く。0.045 を払う $100m の契約は 1.69（$m）。",
        is_new=True,
    ),
    FigureSpec(
        "varswap_replication",
        "exotics",
        "離散ストリップの格子誤差と翼の欠落",
        "Heston の歪んだスマイルで、式26.8の和と閉形式 E(V) の差を行使価格の間隔と範囲ごとに測る。",
        lambda: variance_swap_lesson_figures()["varswap_replication"],
        practice="連続積分としての式26.6は Heston 3市場で閉形式と差 1.5e-12 以内。広い範囲では ΔK を半分にすると誤差がほぼ1/4、狭い範囲では翼の欠落で負に転じ、細かくしても消えない。",
        is_new=True,
    ),
    FigureSpec(
        "volswap_convexity",
        "exotics",
        "ボラ・スワップの凸性補正（式26.9）",
        "E(σ)≈√E(V){1−var(V)/(8E(V)²)} を厳密 E(√V)（CIR ラプラス変換）と MC ±4SE に対して測る。",
        lambda: variance_swap_lesson_figures()["volswap_convexity"],
        practice="Example 26.5 は 0.2484・1.82（$m）。ボラ・スワップには分散の分散が必要で、満期1本のオプションの束だけでは追加の仮定なしに決まらない。この市場では近似はどの ξ でも下側で、誤差は小さい ξ で ξ⁴ に比例して広がる（ξ=1 で −0.46%pt）。",
        is_new=True,
    ),
    FigureSpec(
        "static_boundary",
        "exotics",
        "静的複製で合わせる2つの境界",
        "§26.17 Figure 26.1。満期の給付と S=60 のノックアウト境界を同時に見る。",
        lambda: static_replication_lesson_figures()["static_boundary"],
        practice="満期の S<60 ではコール給付を合わせる。S=60 の境界は離散時刻でだけゼロに合わせる。",
        is_new=True,
    ),
    FigureSpec(
        "static_ladder",
        "exotics",
        "Table 26.1 の4本のコール",
        "原典の A–D のポジションと初期価値。負の B 脚が全体を大きく相殺する。",
        lambda: static_replication_lesson_figures()["static_ladder"],
        practice="独立した線形方程式で計算すると A=1、B≈−2.66、C≈0.97、D≈0.28。合計0.7303で、解析バリア価格0.3136とは異なる。",
        is_new=True,
    ),
    FigureSpec(
        "static_boundary_error",
        "exotics",
        "境界の節点間に残る誤差",
        "3・18・100点のバリア境界で、合わせた時刻とその間の価値を比較する。",
        lambda: static_replication_lesson_figures()["static_boundary_error"],
        practice="選んだ節点では価値がほぼゼロでも、その間や満期直前は一致しない。バリアに触れたらポートフォリオを解消する。",
        is_new=True,
    ),
    FigureSpec(
        "static_convergence",
        "exotics",
        "3・18・100点と解析バリア価格",
        "初期価値0.73→0.38→0.32と、連続監視の解析価格0.3136を比較する。",
        lambda: static_replication_lesson_figures()["static_convergence"],
        practice="点数を増やすとこの市場では近づくが、節点間の完全複製や誤差上界は保証しない。",
        is_new=True,
    ),
    FigureSpec(
        "asian_vs_european",
        "exotics",
        "アジアン vs ヨーロピアン",
        "平均価格は終端価格よりボラが低い → アジアンはヨーロピアンより割安(Hull §26.12)。",
        pv.plotly_asian_vs_european,
        practice="平均はブレが小さい → アジアンは割安。商品・為替の実需に合う構造。",
        is_new=True,
    ),
]


_FRONTIER_SPECS = (
    (
        "ml_price_error",
        "ml_derivatives",
        "ML価格誤差サーフェス",
        "moneyness×maturityで平均値に隠れる局所誤差を確認。",
        "surrogateの危険領域を配置前に特定する。",
    ),
    (
        "ml_greek_error",
        "ml_derivatives",
        "Differential MLのGreek誤差",
        "Delta/Gammaの誤差を同じsplitで比較。",
        "価格精度だけでなくhedge入力の品質を検証する。",
    ),
    (
        "ml_hard_violations",
        "ml_derivatives",
        "soft lossとhard無裁定検査",
        "小型ablationとpenalty_weight 0の本番モデルの違反件数をhard checkで測る。",
        "soft lossをarbitrage-freeの証明と取り違えない。",
    ),
    (
        "ml_speed",
        "ml_derivatives",
        "teacherとsurrogateのbreak-even",
        "batch size別のCPU latency。",
        "較正内の反復呼出しで近似器が効く規模を判断する。",
    ),
    (
        "surface_fit",
        "ml_derivatives",
        "hard-constrained IV fit",
        "市場surfaceと制約付きfitを満期別に重ねる。",
        "repricingとsurface shapeを同時に監視する。",
    ),
    (
        "surface_identifiability",
        "ml_derivatives",
        "識別性とrepricing誤差",
        "同じ価格誤差でもparameter errorが異なる。",
        "parameter解釈よりrepricing riskを優先すべき場面を示す。",
    ),
    (
        "surface_arbitrage",
        "ml_derivatives",
        "fitと無裁定のtrade-off",
        "unconstrained/hard surfaceの形状診断。",
        "見かけのfit改善が静的裁定を生まないか検査する。",
    ),
    (
        "variance_consistency",
        "ml_derivatives",
        "IVとvariance termの同時較正",
        "IV-onlyとjoint lossの期間構造。",
        "VIX系商品とSPX smileの整合を確認する。",
    ),
    (
        "forecast_paths",
        "ml_derivatives",
        "leakage-free RV forecast",
        "Log-HARとPCA-ridgeを同じwalk-forward窓で比較。",
        "複雑モデルを単純baselineより先に採用しない。",
    ),
    (
        "forecast_metrics",
        "ml_derivatives",
        "forecast metricと不確実性",
        "RMSEとQLIKEをモデル別に比較。",
        "metric選択で順位が変わるmodel riskを可視化する。",
    ),
    (
        "hedge_pnl",
        "ml_derivatives",
        "common-path hedge P&L",
        "同じscenarioでstrategy別P&L分布を比較。",
        "予測改善が実際のhedging errorへ届くか確認する。",
    ),
    (
        "hedge_economics",
        "ml_derivatives",
        "CVaRとturnover",
        "tail riskと取引量を同時表示。",
        "低誤差でも過剰売買なら採用しない。",
    ),
    (
        "spx_joint_fit",
        "volatility_frontiers",
        "SPX IV joint fit",
        "PDV/AFVのSPX smile（固定パラメータの比較、較正はしない）。",
        "VIXも同時に合う状態モデルを選ぶ。",
    ),
    (
        "vix_joint_fit",
        "volatility_frontiers",
        "VIX term structure joint fit",
        "VIX futures proxyの期間構造。",
        "SPXだけの過学習をVIX側から検査する。",
    ),
    (
        "joint_model_error",
        "volatility_frontiers",
        "PDV・AFV・rough・quintic比較",
        "SPX/VIX誤差を同じ表で比較。",
        "単一市場のfitだけでモデルを決めない。",
    ),
    (
        "nested_mc_speed",
        "volatility_frontiers",
        "nested MCとsurrogate",
        "batch size別のteacher/surrogate速度。",
        "joint calibrationの計算予算を見積もる。",
    ),
    (
        "zero_dte_clock",
        "volatility_frontiers",
        "0DTE variance clock",
        "暦時間と異なる日中varianceの進み方。",
        "open/closeへ集中するriskを正しい時計で測る。",
    ),
    (
        "zero_dte_jump",
        "volatility_frontiers",
        "scheduled jump intensity",
        "event日と非event日を分離。",
        "FOMC等の既知時刻riskを通常拡散へ混ぜない。",
    ),
    (
        "zero_dte_expiry",
        "volatility_frontiers",
        "隣接expiryのtotal variance",
        "満期を跨ぐtotal variance consistency。",
        "0DTE quoteのcalendar arbitrageを検査する。",
    ),
    (
        "zero_dte_ood",
        "volatility_frontiers",
        "時刻別price/Greek誤差",
        "open/midday/event/closeのevent対baselineのMAE。",
        "平均誤差が隠すevent windowを監視する。",
    ),
    (
        "rfr_compounding",
        "rates_swaps",
        "RFR離散複利と連続極限",
        "daily compoundingとcontinuous limitを比較。",
        "lookback/lockout等の規約実装を手計算で検査する。",
    ),
    (
        "rfr_convexity",
        "rates_swaps",
        "futures-forward convexity",
        "満期別convexity adjustment。",
        "futures quoteをforwardと同一視しない。",
    ),
    (
        "rfr_smile",
        "rates_swaps",
        "Bachelierとshifted SABR",
        "負金利を含むnormal/shifted smile。",
        "近似式のwing・long maturity model riskを見る。",
    ),
    (
        "rfr_delta",
        "rates_swaps",
        "sticky-strikeとBartlett delta",
        "二つのhedge conventionの誤差。",
        "smile moveを含むdelta選択を経済損失で比べる。",
    ),
    (
        "perpetual_prices",
        "crypto_market",
        "index・mark・last price",
        "三つの価格stateをstress pathで分離。",
        "清算とfundingの参照価格混同を防ぐ。",
    ),
    (
        "liquidation_waterfall",
        "crypto_market",
        "insurance fundとADL",
        "清算損失のwaterfallを追跡。",
        "fund枯渇後のsocialized lossを可視化する。",
    ),
    (
        "crypto_solvency",
        "crypto_market",
        "solvency ledger",
        "equity/liabilityのstress推移。",
        "全cash flowが保存則に合うか確認する。",
    ),
    (
        "amm_lvr",
        "crypto_market",
        "AMM LVRとfee補償",
        "LVR・固定fee・dynamic feeを分離。",
        "fee収益をLVR削減と取り違えない。",
    ),
    (
        "carbon_smile",
        "climate_energy",
        "carbon GBMとSV+jump",
        "jump riskがcarbon option smileへ与える影響。",
        "return/variance/jump premiumを分けて感応度管理する。",
    ),
    (
        "weather_paths",
        "climate_energy",
        "temperature OUとfOU",
        "seasonality・短期平均回帰・long memory。",
        "weather payoffの期間依存をモデル別に見る。",
    ),
    (
        "weather_basis",
        "climate_energy",
        "station/location basis risk",
        "距離とindex mismatchの誤差。",
        "非取引可能な現地weather riskの残差を測る。",
    ),
    (
        "ppa_risk",
        "climate_energy",
        "PPA shape・volume・profile risk",
        "CVaRとhedge residualをrisk別に比較。",
        "fair valueとcash-flow-at-riskを別々に報告する。",
    ),
)


def _artifact_figures(specs: tuple[tuple[str, str, str, str, str], ...]) -> list[FigureSpec]:
    """Artifact-backed figures whose builders live in ``frontier_figures``."""
    return [
        FigureSpec(
            figure_id,
            book,
            title,
            blurb,
            ff.FRONTIER_BUILDERS[figure_id],
            practice=practice,
            is_new=True,
        )
        for figure_id, book, title, blurb, practice in specs
    ]


FIGURES.extend(_artifact_figures(_FRONTIER_SPECS))


# Beyond A5--A8: inflation/JGBi (vol 26), the risk desk (vol 27) and the credit
# desk (vol 28), also artifact-backed and read via ``frontier_figures``.
_BEYOND_SPECS = (
    (
        "inflation_curves",
        "rates_swaps",
        "名目・実質割引カーブ",
        "名目と実質の割引factorを満期別に。両者の比がbreakeven inflationを決める。",
        "名目・実質カーブからBEIを読む。インフレ連動債値付けの出発点。",
    ),
    (
        "inflation_swaps",
        "rates_swaps",
        "ゼロクーポンインフレスワップの再評価",
        "committed ZCIS quoteと再評価値を満期別に比較。再評価誤差は恒等式でゼロ。",
        "市場ZCISからインフレカーブを較正した整合性の検算。",
    ),
    (
        "jgbi_floor",
        "rates_swaps",
        "JGBiデフレフロアとインフレボラ",
        "元本フロア価値をインフレボラ別に。analyticは単調増加、MCと標準誤差内で一致。",
        "デフレ時の元本保証(フロア)の価値。ボラが上がるほど厚くなるオプション価値。",
    ),
    (
        "jgbi_bei",
        "rates_swaps",
        "raw vs フロア調整後BEI",
        "生のbreakeven inflationと、デフレフロアを織り込んだ調整後BEIの差。",
        "フロア(オプション性)を無視した素朴なBEIが割高評価になる点の可視化。",
    ),
    (
        "var_traffic_light",
        "risk_management",
        "Baselトラフィックライトと資本乗数",
        "超過回数ごとの二項ゾーン(緑/黄/赤)と資本乗数のステップ。250日99%の枠組み。",
        "バックテスト超過が資本add-onへ翻訳される規制の仕組みを一望する。",
    ),
    (
        "fhs_vs_hs_coverage",
        "risk_management",
        "FHS vs 素朴HSのVaRカバレッジ",
        "ローリングVaR予測(HS/FHS)と違反日。FHSは条件付ボラで違反率を1%へ近づける。",
        "危機時のVaR過小評価をFHSが是正する様子。カバレッジ改善の実証。",
    ),
    (
        "gpd_tail_fit",
        "risk_management",
        "GPDテールフィットと平均超過",
        "経験VaR ladderとGPD(POT)フィット分位、横に平均超過プロット。",
        "希少テール(0.1%)の外挿。経験分位が尽きる領域をEVTで埋める。",
    ),
    (
        "risk_allocation_bars",
        "risk_management",
        "コンポーネントVaR/ESの配賦",
        "資産別のcomponent VaRとES。Euler配賦で合計はポート全体に厳密一致(加法性)。",
        "リスク限度をデスク別に割り当てる。合計がポート値に一致する配賦の実務。",
    ),
    (
        "cds_leg_pv_by_year",
        "risk_credit",
        "CDS レッグの年別 PV（Hull Table 25.2–25.4）",
        "期待支払い・アクルーアル・ペイオフの現在価値を年別に。合計 4.1150s と 0.0506 の比が 123bp。",
        "CDS を『リスキー年金 × スプレッド = 期待損失』に分解して読む。デスクの MTM の骨格。",
    ),
    (
        "tranche_spread_vs_correlation",
        "risk_credit",
        "CDO トランシェスプレッド vs 相関",
        "Ex 25.2 の設定で 6 トランシェのブレークイーブンスプレッドを ρ で動かす。エクイティは下がりシニアは上がる。",
        "相関は損失の期待値を変えずに分布をトランシェ間で動かす。2008 年のシニアの崩れ方。",
    ),
    (
        "base_correlation_skew",
        "risk_credit",
        "コンパウンド相関のスマイルとベース相関のスキュー",
        "iTraxx 2007-01-31 の気配（Table 25.6）から逆算した相関。Hull Table 25.8 の印刷値を重ねる。",
        "ガウシアンコピュラが市場と整合しない証拠。ベース相関で非標準トランシェを補間する実務。",
    ),
    (
        "creditmetrics_loss_distribution",
        "risk_credit",
        "CreditMetrics 損失分布と信用 VaR",
        "Table 24.4 の推移行列と 1 ファクター相関で 100 社の損失を模擬。ρ=0.2 で 99.9% VaR が伸びる。",
        "格下げも損失に数える信用 VaR。規制資本の Vasicek 式との対応。",
    ),
)

FIGURES.extend(_artifact_figures(_BEYOND_SPECS))


def figures_for(book: str) -> list[FigureSpec]:
    return [f for f in FIGURES if f.book == book]
