"""Offline, self-contained HTML report.

Assembles styled Plotly figures and notes into a single HTML file that opens with
no network: ``plotly.js`` is embedded **inline once** (the first figure), and the
rest reference it. ``strategy_report`` wires the standard sections (metrics,
equity, drawdown, distribution, rolling Sharpe, optional IC and cost sweep, plus
caveats) straight from the objects the platform already produces.
"""

from __future__ import annotations

from html import escape
from pathlib import Path

import plotly.graph_objects as go

from . import figures

_TEMPLATE = """<!doctype html>
<html lang="ja"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
 body{{font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif;color:#111;
   max-width:1040px;margin:0 auto;padding:36px 24px;line-height:1.65}}
 h1{{font-weight:700;letter-spacing:-0.02em;margin-bottom:.1em}}
 h2{{margin-top:2.4em;border-bottom:1px solid #eee;padding-bottom:.3em;font-weight:600}}
 .sub{{color:#777;margin-top:0}} .desc{{color:#444}}
 .fig{{margin:1.1em 0}}
 .note{{background:#fafafa;border-left:3px solid #ddd;padding:.7em 1em;color:#555;font-size:.93em;border-radius:2px}}
 footer{{margin-top:3.5em;color:#999;font-size:.85em;border-top:1px solid #eee;padding-top:1em}}
</style></head>
<body>
<h1>{title}</h1>
<p class="sub">{subtitle}</p>
{body}
<footer>{footer}</footer>
</body></html>"""


def _fig_html(fig: go.Figure, *, include_js: bool) -> str:
    return fig.to_html(
        full_html=False,
        include_plotlyjs="inline" if include_js else False,
        config={"displayModeBar": False, "responsive": True},
    )


def build_report(
    title: str,
    sections: list[dict],
    out_path: str | Path,
    *,
    subtitle: str = "",
    footer: str = "Generated by irp.visualization — research only, not investment advice.",
) -> Path:
    """Write ``sections`` to a self-contained HTML file at ``out_path``.

    Each section is a dict: ``heading`` (str), optional ``description`` (str),
    optional ``figures`` (list of Figure), optional ``note`` (str). plotly.js is
    embedded once, on the first figure encountered.
    """
    blocks: list[str] = []
    first = True
    for sec in sections:
        parts = [f"<h2>{escape(sec['heading'])}</h2>"]
        if sec.get("description"):
            parts.append(f"<p class='desc'>{sec['description']}</p>")
        for fig in sec.get("figures", []):
            parts.append(f"<div class='fig'>{_fig_html(fig, include_js=first)}</div>")
            first = False
        if sec.get("note"):
            parts.append(f"<p class='note'>{sec['note']}</p>")
        blocks.append("\n".join(parts))
    html = _TEMPLATE.format(
        title=escape(title),
        subtitle=escape(subtitle),
        body="\n".join(blocks),
        footer=escape(footer),
    )
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    return out


def strategy_report(
    results: dict,
    out_path: str | Path,
    *,
    title: str = "IRP strategy report",
    subtitle: str = "",
    ic=None,
    cost_sweep=None,
    periods: int = 252,
    primary: str | None = None,
    notes: str | None = None,
) -> Path:
    """Build the standard strategy report from a dict of backtests + baselines."""
    from ..backtest.metrics import compare

    cmp = compare(results, periods=periods)
    primary = primary or next(iter(results))
    res0 = results[primary]

    sections: list[dict] = [
        {
            "heading": "Summary metrics",
            "description": "Strategy vs baselines/benchmark, annualized. Always read against a baseline.",
            "figures": [figures.metrics_table(cmp)],
        },
        {
            "heading": "Equity curves",
            "description": "Cumulative growth of 1 unit, net of costs.",
            "figures": [figures.equity_curves(results)],
        },
        {
            "heading": "Drawdown",
            "description": f"Underwater plot for <b>{escape(primary)}</b>.",
            "figures": [figures.drawdown(res0)],
        },
        {
            "heading": "Return distribution & rolling Sharpe",
            "figures": [
                figures.returns_histogram(res0),
                figures.rolling_sharpe(res0, periods=periods),
            ],
        },
    ]
    if ic is not None:
        sections.append(
            {
                "heading": "Information coefficient",
                "description": "Mean cross-sectional rank IC (out-of-sample).",
                "figures": [figures.ic_bar(ic)],
            }
        )
    if cost_sweep is not None:
        sections.append(
            {
                "heading": "Cost sensitivity",
                "description": "Sharpe as transaction cost rises (turnover drag).",
                "figures": [figures.cost_sensitivity(cost_sweep)],
            }
        )
    sections.append(
        {
            "heading": "Notes & caveats",
            "note": notes
            or "Research only — not investment advice. Figures may use synthetic/illustrative "
            "data; transaction costs, slippage and taxes are assumptions held in configs/. "
            "Complex models are shown next to simple baselines, including when they fail.",
        }
    )
    return build_report(title, sections, out_path, subtitle=subtitle)
